const COUNTS=[7,286,200,176,120,165,206,75,129,109,123,111,43,52,99,128,111,110,98,135,112,78,118,64,77,227,93,88,69,60,34,30,73,54,45,83,182,88,75,85,54,53,89,59,37,35,38,29,18,45,60,49,62,55,78,96,29,22,24,13,14,11,11,18,12,12,30,52,52,44,28,28,20,56,40,31,50,40,46,42,29,19,36,25,22,17,19,26,30,20,15,21,11,8,8,19,5,8,8,11,11,8,3,9,5,4,7,3,6,3,5,4,5,6];
const NAMES=['الفاتحة','البقرة','آل عمران','النساء','المائدة','الأنعام','الأعراف','الأنفال','التوبة','يونس','هود','يوسف','الرعد','إبراهيم','الحجر','النحل','الإسراء','الكهف','مريم','طه','الأنبياء','الحج','المؤمنون','النور','الفرقان','الشعراء','النمل','القصص','العنكبوت','الروم','لقمان','السجدة','الأحزاب','سبأ','فاطر','يس','الصافات','ص','الزمر','غافر','فصلت','الشورى','الزخرف','الدخان','الجاثية','الأحقاف','محمد','الفتح','الحجرات','ق','الذاريات','الطور','النجم','القمر','الرحمن','الواقعة','الحديد','المجادلة','الحشر','الممتحنة','الصف','الجمعة','المنافقون','التغابن','الطلاق','التحريم','الملك','القلم','الحاقة','المعارج','نوح','الجن','المزمل','المدثر','القيامة','الإنسان','المرسلات','النبأ','النازعات','عبس','التكوير','الانفطار','المطففين','الانشقاق','البروج','الطارق','الأعلى','الغاشية','الفجر','البلد','الشمس','الليل','الضحى','الشرح','التين','العلق','القدر','البينة','الزلزلة','العاديات','القارعة','التكاثر','العصر','الهمزة','الفيل','قريش','الماعون','الكوثر','الكافرون','النصر','المسد','الإخلاص','الفلق','الناس'];
const startOf=s=>1+COUNTS.slice(0,s-1).reduce((a,b)=>a+b,0);
async function timed(url,ms=10000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{signal:c.signal,headers:{accept:'application/json'}})}finally{clearTimeout(t)}}
const json=(data,status=200,cache='public, max-age=3600, s-maxage=86400')=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':cache,'access-control-allow-origin':'*'}});
function fromQuranCom(verses,page){const ayahs=(verses||[]).map(v=>{const k=String(v.verse_key||'').split(':').map(Number),s=Number(v.chapter_id)||k[0],a=Number(v.verse_number)||k[1];return{number:Number(v.id)||startOf(s)+a-1,numberInSurah:a,text:v.text_uthmani||'',juz:Number(v.juz_number)||null,page:Number(v.page_number)||page,surah:{number:s,name:NAMES[s-1]||`سورة ${s}`,numberOfAyahs:COUNTS[s-1]||0}}}).filter(a=>a.text&&a.surah.number&&a.numberInSurah);if(!ayahs.length)throw Error('empty');return ayahs}
async function mushaf(page){try{const r=await timed(`https://api.quran.com/api/v4/verses/by_page/${page}?language=ar&words=false&fields=text_uthmani&per_page=50`);if(r.ok){const j=await r.json();return json({ok:true,page,source:'quran.com',ayahs:fromQuranCom(j.verses,page)})}}catch(e){}try{const r=await timed(`https://api.alquran.cloud/v1/page/${page}/quran-uthmani`);if(!r.ok)throw Error('source');const j=await r.json(),ayahs=(j.data?.ayahs||[]).map(a=>({number:a.number,numberInSurah:a.numberInSurah,text:a.text,juz:a.juz,page:a.page,surah:{number:a.surah?.number,name:a.surah?.name,numberOfAyahs:a.surah?.numberOfAyahs}}));if(!ayahs.length)throw Error('empty');return json({ok:true,page,source:'alquran.cloud',ayahs})}catch(e){return json({ok:false,page,error:'MUSHAF_SOURCE_UNAVAILABLE'},502,'no-store')}}
async function hisnFallback(path){const r=await timed('https://raw.githubusercontent.com/SalehGNUTUX/GT_HISNMUSLIM/main/hisnmuslim.json',12000);if(!r.ok)throw Error('fallback');const all=await r.json();if(!Array.isArray(all)||!all.length)throw Error('empty');if(path==='index'){return {'العربية':all.map(x=>({ID:Number(x.id),TITLE:String(x.category||''),AUDIO_URL:x.audio||'',TEXT:String(x.id)+'.json'})).filter(x=>x.ID&&x.TITLE)}}const d=all.find(x=>Number(x.id)===Number(path));if(!d)throw Error('door');return {[String(d.category||'حصن المسلم')]:Array.isArray(d.array)?d.array.map(x=>({ID:Number(x.id)||0,ARABIC_TEXT:String(x.text||''),REPEAT:Number(x.count)||1,AUDIO:x.audio||''})):[]}}
async function hisn(path){const target=path==='index'?'https://hisnmuslim.com/api/ar/husn_ar.json':`https://hisnmuslim.com/api/ar/${Number(path)}.json`;try{const r=await timed(target);if(!r.ok)throw Error('source');const data=await r.json();return json({ok:true,data,source:'hisnmuslim.com'},200,'no-store')}catch(e){try{return json({ok:true,data:await hisnFallback(path),source:'verified-fallback'},200,'no-store')}catch(_){return json({ok:false,error:'HISN_SOURCE_UNAVAILABLE'},502,'no-store')}}}
export default{async fetch(request,env){const u=new URL(request.url);let m=u.pathname.match(/^\/api\/mushaf\/(\d+)$/);if(m)return mushaf(Math.max(1,Math.min(604,Number(m[1])||1)));m=u.pathname.match(/^\/api\/hisn\/(index|\d+)$/);if(m)return hisn(m[1]);return env.ASSETS.fetch(request)}};