// Compact RTL desktop dashboard for Werd. Mobile remains untouched.
(function(){
  const MQ='(min-width:960px)';
  const items=[['⌂','الرئيسية','home'],['📖','المصحف','quran'],['🌿','الأذكار','adhkar'],['📿','المسبحة','tasbih'],['🎧','الاستماع','listening'],['🧠','متابعة الحفظ','memorizationTracker'],['🗺','رحلة الحفظ','memorizationJourney'],['📅','خطة اليوم','dailyMemorizationPlan'],['▦','الخطة الأسبوعية','weeklyMemorizationPlan'],['🎯','الهدف طويل المدى','longTermMemGoal'],['🏅','الإنجازات','advancedAchievements'],['📊','الإحصائيات','stats'],['☷','المزيد','more']];
  function injectCss(){if(document.getElementById('werdDesktopCss'))return;const s=document.createElement('style');s.id='werdDesktopCss';s.textContent=`
  @media(min-width:960px){
    html,body{min-height:100%;background:#f3efe7}body{overflow-x:hidden;font-family:"Segoe UI",Tahoma,Arial,sans-serif!important;font-size:16px!important;line-height:1.55!important}
    .app{max-width:none!important;width:100%!important;min-height:100vh;margin:0!important;padding:88px 278px 30px 24px!important;background:var(--bg)}
    main{max-width:1480px!important;width:100%!important;margin:0 auto!important;display:block!important;min-width:0}.page{width:100%!important;min-width:0}.page.active{display:block!important}
    .top{position:fixed!important;z-index:45;top:0;right:0;left:0;height:68px;margin:0!important;padding:8px 278px 8px 24px!important;background:rgba(255,253,248,.97);border-bottom:1px solid var(--line);box-shadow:0 4px 14px rgba(32,57,48,.035);backdrop-filter:blur(14px)}
    .top .brand{margin:auto}.top .brand h1{font-size:22px!important}.top .brand small{font-size:12px!important}.top .logo{width:46px;height:46px;border-radius:14px;font-size:19px}.top .actions{position:absolute;left:24px;direction:ltr}.iconbtn{width:40px;height:40px;border-radius:12px}
    .bottom{position:fixed!important;z-index:50;top:0!important;right:0!important;left:auto!important;bottom:0!important;transform:none!important;width:254px!important;height:100vh!important;display:flex!important;flex-direction:column;gap:2px;padding:82px 12px 18px!important;background:rgba(255,253,248,.985);border:0;border-left:1px solid var(--line);box-shadow:-6px 0 20px rgba(30,60,48,.03);overflow:auto;backdrop-filter:blur(16px)}
    .bottom:before{content:'ورد';font-weight:900;font-size:20px;color:var(--green);padding:0 11px 9px;border-bottom:1px solid var(--line);margin-bottom:5px}.nav{display:flex!important;align-items:center;gap:10px;width:100%!important;min-height:40px;flex:0 0 auto;border-radius:10px;padding:8px 11px!important;font-size:14px!important;font-weight:650;text-align:right;direction:rtl;transition:.14s}.nav i{display:grid;place-items:center;width:24px;font-size:18px}.nav:hover{background:#eef3eb;color:var(--green)}.nav.active{background:var(--sage);color:var(--green);font-weight:850}.desktop-extra-nav{display:contents}
    h1,h2,h3,h4,b,strong{font-family:"Segoe UI",Tahoma,Arial,sans-serif}.hero{border-radius:18px;padding:20px 22px}.hero h2{font-size:28px!important;line-height:1.35;margin:5px 0}.hero p{font-size:15px!important;line-height:1.55;margin-bottom:11px}.eyebrow,.hero-meta{font-size:13px!important}.primary,.secondary{padding:11px 14px!important;margin-top:10px!important;font-size:15px!important;border-radius:13px!important}
    .card{border-radius:15px;padding:15px 16px;margin-bottom:0!important}.card b,.list-item b{font-size:16px}.muted{font-size:13px!important;line-height:1.5}.badge{font-size:12px!important;padding:5px 8px}.section-title{margin:13px 2px 7px!important}.section-title h3{font-size:18px!important}.section-title span{font-size:12px!important}.list-item{padding:9px 0}.smallbtn{font-size:13px!important;padding:7px 9px!important;border-radius:10px!important}
    .grid{grid-template-columns:repeat(6,minmax(0,1fr));gap:9px}.tile{border-radius:14px;min-height:86px!important;display:grid;align-content:center;padding:11px 8px}.tile .em{font-size:25px}.tile b{font-size:14px!important;margin-top:4px}.statgrid{grid-template-columns:repeat(3,minmax(0,1fr));gap:9px}.stat{padding:11px}.stat b{font-size:22px}
    .search input{font-size:15px!important}.chip{font-size:13px!important;padding:8px 10px!important}.surah{padding:10px 0}.surah b{font-size:15px}.surah small{font-size:12px}.num{font-size:14px;width:35px;height:35px}

    /* Dense homepage: no forced empty card heights. */
    #home.active{display:grid!important;grid-template-columns:repeat(12,minmax(0,1fr))!important;gap:10px!important;align-items:start!important}
    #home.active>*{min-width:0!important;max-width:none!important;margin-top:0!important;margin-bottom:0!important}
    #home.active>.hero{grid-column:span 8!important;align-self:stretch}
    #home.active>#authCard{grid-column:span 4!important;align-self:stretch}
    #home.active>#installCard{grid-column:span 4!important}
    #home.active>#smartDashboard{grid-column:1/-1!important;width:100%!important;display:block!important}
    #home.active>#smartDashboard .smart-head{margin:10px 0 6px!important}.smart-head h3{font-size:17px!important}.smart-head span{font-size:11px!important}
    #home.active>#smartDashboard .smart-grid{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:9px!important;align-items:stretch!important}
    #home.active>#smartDashboard .smart-card{min-width:0!important;min-height:0!important;height:auto!important;padding:13px 14px!important;border-radius:14px!important;justify-content:flex-start!important;gap:7px!important}
    #home.active>#smartDashboard .smart-card.wide{grid-column:span 1!important}
    #home.active>#smartDashboard .smart-card .sc-big{font-size:21px!important;margin-top:3px!important}.smart-card .sc-icon{font-size:20px!important}.smart-card .sc-kicker{font-size:10px!important}.smart-card .sc-sub{font-size:12px!important;line-height:1.45!important;margin-top:2px!important}.smart-card .sc-action{font-size:12px!important;padding-top:4px!important;margin-top:auto!important}.smart-progress{margin-top:5px!important;height:5px!important}.smart-dhikr-text{font-size:14px!important;line-height:1.7!important;margin:4px 0!important}
    #home.active>#smartDashboard .smart-quick{display:grid!important;grid-template-columns:repeat(6,minmax(0,1fr))!important;gap:7px!important;overflow:visible!important;padding:0!important}#home.active>#smartDashboard .smart-quick button{width:100%;white-space:normal!important;min-height:40px!important;padding:8px!important;font-size:12px!important;border-radius:11px!important}
    #home.active>.section-title{grid-column:1/-1!important;margin:9px 2px 2px!important}#home.active>.grid{grid-column:1/-1!important}#home.active>.card:not(#authCard):not(#installCard){grid-column:span 6!important}#home.active>.offline{grid-column:1/-1!important;margin:0!important;padding:8px 11px!important}
    #home .home-old-last{display:none!important}

    #quran.active,#adhkar.active,#tasbih.active,#plan.active,#stats.active,#listening.active{max-width:1240px!important;margin:0 auto!important}#listening.active .listen-hero{max-width:760px;margin:0 auto 9px}.listen-selects{grid-template-columns:1fr 1fr!important}.mini-player{bottom:18px!important;left:24px!important;right:auto!important;transform:none!important;width:min(620px,calc(100% - 330px))!important;font-size:14px!important}.reader-head{top:68px}.ayah{font-family:"Traditional Arabic","Geeza Pro",serif!important;font-size:30px!important;line-height:2.2!important}.dhikr{font-family:"Traditional Arabic","Geeza Pro",serif!important;font-size:24px!important;line-height:2.1!important}.counter-circle{width:230px;height:230px}.mjour-grid,.aach-grid{grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:9px!important}.mjour-juz-grid{grid-template-columns:repeat(6,minmax(0,1fr))!important;gap:8px!important}
  }
  @media(min-width:960px) and (max-width:1180px){.app{padding-right:224px!important;padding-left:16px!important}.top{padding-right:224px!important;padding-left:16px!important}.bottom{width:208px!important}.top .actions{left:16px}.nav{font-size:13px!important}#home.active>.hero,#home.active>#authCard,#home.active>#installCard{grid-column:1/-1!important}#home.active>#smartDashboard .smart-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}.grid{grid-template-columns:repeat(3,minmax(0,1fr))}.mjour-grid,.aach-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}.mjour-juz-grid{grid-template-columns:repeat(4,minmax(0,1fr))!important}.mini-player{left:16px!important;width:calc(100% - 256px)!important}}
  @media(min-width:1450px){.app{padding-right:292px!important;padding-left:30px!important}.top{padding-right:292px!important;padding-left:30px!important}.bottom{width:266px!important}.top .actions{left:30px}#home.active>#smartDashboard .smart-grid{grid-template-columns:repeat(4,minmax(0,1fr))!important}#home.active>#smartDashboard .smart-card.wide{grid-column:span 2!important}.mjour-grid{grid-template-columns:repeat(5,minmax(0,1fr))!important}}
    body.dark .bottom,body.dark .top{background:rgba(22,40,33,.97)}
  `;document.head.appendChild(s)}
  function addNav(){const nav=document.querySelector('.bottom');if(!nav||document.getElementById('desktopExtraNav'))return;const wrap=document.createElement('div');wrap.id='desktopExtraNav';wrap.className='desktop-extra-nav';const existing=new Set([...nav.querySelectorAll('[data-page]')].map(x=>x.dataset.page));for(const [icon,label,page] of items){if(existing.has(page))continue;const b=document.createElement('button');b.className='nav';b.dataset.page=page;b.innerHTML=`<i>${icon}</i>${label}`;b.onclick=()=>open(page);wrap.appendChild(b)}nav.appendChild(wrap)}
  function open(page){if(document.getElementById(page)){go(page);return}const map={memorizationTracker:'openWerdMemorizationTracker',memorizationJourney:'openWerdMemorizationJourney',dailyMemorizationPlan:'openWerdDailyMemorizationPlan',weeklyMemorizationPlan:'openWerdWeeklyMemorizationPlan',longTermMemGoal:'openWerdLongTermMemGoal',advancedAchievements:'openWerdAdvancedAchievements'};const fn=window[map[page]];if(typeof fn==='function')fn();else if(typeof go==='function')go('more')}
  function sync(){if(!matchMedia(MQ).matches)return;const active=document.querySelector('main .page.active')?.id;document.querySelectorAll('.bottom .nav').forEach(b=>b.classList.toggle('active',b.dataset.page===active))}
  function init(){injectCss();addNav();sync();const main=document.querySelector('main');if(main)new MutationObserver(sync).observe(main,{subtree:true,attributes:true,attributeFilter:['class']});window.addEventListener('resize',sync)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();