// Balanced RTL desktop shell for Werd. Mobile remains untouched.
(function(){
  const MQ='(min-width:960px)';
  const items=[['⌂','الرئيسية','home'],['📖','المصحف','quran'],['🌿','الأذكار','adhkar'],['📿','المسبحة','tasbih'],['🎧','الاستماع','listening'],['🧠','متابعة الحفظ','memorizationTracker'],['🗺','رحلة الحفظ','memorizationJourney'],['📅','خطة اليوم','dailyMemorizationPlan'],['▦','الخطة الأسبوعية','weeklyMemorizationPlan'],['🎯','الهدف طويل المدى','longTermMemGoal'],['🏅','الإنجازات','advancedAchievements'],['📊','الإحصائيات','stats'],['☷','المزيد','more']];
  function injectCss(){if(document.getElementById('werdDesktopCss'))return;const s=document.createElement('style');s.id='werdDesktopCss';s.textContent=`
  @media(min-width:960px){
    html,body{min-height:100%;background:#f4f0e8}body{overflow-x:hidden;font-family:Tahoma,"Segoe UI",Arial,sans-serif!important;font-size:17px!important;line-height:1.7!important;letter-spacing:0!important}
    .app{max-width:none!important;width:100%!important;min-height:100vh;margin:0!important;padding:104px 300px 56px 34px!important;background:var(--bg)}main{max-width:1320px!important;width:100%!important;margin:0 auto!important;display:block!important;min-width:0}.page{width:100%!important;min-width:0}.page.active{display:block!important}
    .top{position:fixed!important;z-index:45;top:0;right:0;left:0;height:82px;margin:0!important;padding:13px 300px 13px 34px!important;background:rgba(255,253,248,.96);border-bottom:1px solid var(--line);box-shadow:0 5px 18px rgba(32,57,48,.04);backdrop-filter:blur(16px)}.top .brand{margin-right:auto;margin-left:auto}.top .brand h1{font-size:25px!important;font-weight:800}.top .brand small{font-size:14px!important}.top .logo{width:52px;height:52px;border-radius:15px;font-size:22px}.top .actions{position:absolute;left:34px;direction:ltr}
    .bottom{position:fixed!important;z-index:50;top:0!important;right:0!important;left:auto!important;bottom:0!important;transform:none!important;width:266px!important;height:100vh!important;display:flex!important;flex-direction:column;gap:5px;padding:105px 14px 24px!important;background:rgba(255,253,248,.98);border:0;border-left:1px solid var(--line);box-shadow:-8px 0 25px rgba(30,60,48,.035);overflow:auto;backdrop-filter:blur(18px)}.bottom:before{content:'ورد';font-weight:900;font-size:22px;color:var(--green);padding:0 13px 12px;border-bottom:1px solid var(--line);margin-bottom:7px}.nav{display:flex!important;align-items:center;gap:12px;width:100%!important;min-height:48px;flex:0 0 auto;border-radius:13px;padding:11px 13px!important;font-size:16px!important;font-weight:700;text-align:right;direction:rtl;transition:.16s}.nav i{display:grid;place-items:center;width:27px;font-size:20px}.nav:hover{background:#eef3eb;color:var(--green)}.nav.active{background:var(--sage);color:var(--green);font-weight:900}.desktop-extra-nav{display:contents}
    h1,h2,h3,h4,b,strong{font-family:Tahoma,"Segoe UI",Arial,sans-serif}.hero{border-radius:22px;padding:28px 30px}.hero h2{font-size:34px!important;line-height:1.45;margin:8px 0}.hero p{font-size:17px!important;line-height:1.8}.eyebrow{font-size:15px!important}.hero-meta{font-size:15px!important}.card{border-radius:18px;padding:21px 22px}.card b,.list-item b{font-size:17px}.muted{font-size:15px!important;line-height:1.65}.badge{font-size:14px!important}.section-title{margin:24px 2px 13px}.section-title h3{font-size:22px!important}.section-title span{font-size:14px!important}.grid{grid-template-columns:repeat(6,minmax(0,1fr));gap:13px}.tile{border-radius:17px;min-height:118px;display:grid;align-content:center;padding:17px 10px}.tile .em{font-size:30px}.tile b{font-size:16px!important;margin-top:8px}.statgrid{grid-template-columns:repeat(3,minmax(0,1fr))}.stat{padding:15px}.stat b{font-size:24px}.smallbtn,.primary,.secondary,.chip,.search input,.search button,select,input,button{font-family:Tahoma,"Segoe UI",Arial,sans-serif}.smallbtn{font-size:14px!important}.primary,.secondary{font-size:17px!important}.search input{font-size:17px!important}.chip{font-size:15px!important}.surah b{font-size:17px}.surah small{font-size:14px}.num{font-size:16px}
    #home.active{display:block!important}#home.active>*{width:100%!important;max-width:none!important;min-width:0!important}#home.active>.hero{margin-bottom:18px}#home.active>#smartDashboard{margin:0 0 18px!important}#home.active>#smartDashboard .smart-grid{display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:13px!important}#home.active>#smartDashboard .smart-card{min-width:0!important;min-height:165px!important;padding:20px!important;border-radius:18px!important;font-size:16px!important}#home.active>#smartDashboard .smart-card b,#home.active>#smartDashboard .smart-card strong{font-size:19px!important}#home.active>#smartDashboard .smart-card .muted,#home.active>#smartDashboard .smart-card small{font-size:14px!important;line-height:1.65}#home.active>#smartDashboard .smart-card.wide{grid-column:span 2!important}#home.active>#smartDashboard .smart-head{margin-top:15px!important}#home.active>#smartDashboard .smart-quick{display:grid!important;grid-template-columns:repeat(6,minmax(0,1fr))!important;gap:9px!important;overflow:visible!important}#home.active>#smartDashboard .smart-quick button{width:100%;white-space:normal!important;min-height:52px;font-size:14px!important}#authCard,#installCard{max-width:100%!important}
    #quran.active,#adhkar.active,#tasbih.active,#plan.active,#stats.active,#listening.active{max-width:1120px!important;margin:0 auto!important}#listening.active .listen-hero{max-width:820px;margin:0 auto 14px}.listen-selects{grid-template-columns:1fr 1fr!important}.mini-player{bottom:24px!important;left:34px!important;right:auto!important;transform:none!important;width:min(600px,calc(100% - 360px))!important;font-size:15px!important}.reader-head{top:82px}.ayah{font-family:"Traditional Arabic","Geeza Pro",serif!important;font-size:32px!important;line-height:2.35!important}.dhikr{font-family:"Traditional Arabic","Geeza Pro",serif!important;font-size:26px!important;line-height:2.2!important}.counter-circle{width:250px;height:250px}.mjour-grid,.aach-grid{grid-template-columns:repeat(3,minmax(0,1fr))!important}.mjour-juz-grid{grid-template-columns:repeat(5,minmax(0,1fr))!important}
  }
  @media(min-width:960px) and (max-width:1180px){.app{padding-right:244px!important;padding-left:22px!important}.top{padding-right:244px!important;padding-left:22px!important}.bottom{width:220px!important}.top .actions{left:22px}.nav{font-size:15px!important}#home.active>#smartDashboard .smart-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}#home.active>#smartDashboard .smart-card.wide{grid-column:1/-1!important}.grid{grid-template-columns:repeat(3,minmax(0,1fr))}.mjour-grid,.aach-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}.mjour-juz-grid{grid-template-columns:repeat(3,minmax(0,1fr))!important}.mini-player{left:22px!important;width:calc(100% - 286px)!important}}
  @media(min-width:1450px){.app{padding-right:318px!important;padding-left:48px!important}.top{padding-right:318px!important;padding-left:48px!important}.bottom{width:282px!important}.top .actions{left:48px}.mjour-grid{grid-template-columns:repeat(4,minmax(0,1fr))!important}}
  body.dark .bottom,body.dark .top{background:rgba(22,40,33,.97)}
  `;document.head.appendChild(s)}
  function addNav(){const nav=document.querySelector('.bottom');if(!nav||document.getElementById('desktopExtraNav'))return;const wrap=document.createElement('div');wrap.id='desktopExtraNav';wrap.className='desktop-extra-nav';const existing=new Set([...nav.querySelectorAll('[data-page]')].map(x=>x.dataset.page));for(const [icon,label,page] of items){if(existing.has(page))continue;const b=document.createElement('button');b.className='nav';b.dataset.page=page;b.innerHTML=`<i>${icon}</i>${label}`;b.onclick=()=>open(page);wrap.appendChild(b)}nav.appendChild(wrap)}
  function open(page){if(document.getElementById(page)){go(page);return}const map={memorizationTracker:'openWerdMemorizationTracker',memorizationJourney:'openWerdMemorizationJourney',dailyMemorizationPlan:'openWerdDailyMemorizationPlan',weeklyMemorizationPlan:'openWerdWeeklyMemorizationPlan',longTermMemGoal:'openWerdLongTermMemGoal',advancedAchievements:'openWerdAdvancedAchievements'};const fn=window[map[page]];if(typeof fn==='function')fn();else if(typeof go==='function')go('more')}
  function sync(){if(!matchMedia(MQ).matches)return;const active=document.querySelector('main .page.active')?.id;document.querySelectorAll('.bottom .nav').forEach(b=>b.classList.toggle('active',b.dataset.page===active))}
  function init(){injectCss();addNav();sync();const main=document.querySelector('main');if(main)new MutationObserver(sync).observe(main,{subtree:true,attributes:true,attributeFilter:['class']});window.addEventListener('resize',sync)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();