// Local Hisn bootstrap v87. A compact built-in index ensures the page renders even when remote APIs are blocked on iOS/PWA.
window.WERD_HISN_LOCAL = [
{id:1,category:'أذكار الصباح والمساء'},
{id:2,category:'أذكار النوم'},
{id:3,category:'الدعاء إذا تقلب ليلاً'},
{id:4,category:'دعاء الفزع في النوم ومن بلي بالوحشة'},
{id:5,category:'ما يفعل من رأى الرؤيا أو الحلم'},
{id:6,category:'دعاء قنوت الوتر'},
{id:7,category:'الذكر عقب السلام من الوتر'},
{id:8,category:'دعاء الهم والحزن'},
{id:9,category:'دعاء الكرب'},
{id:10,category:'دعاء لقاء العدو وذي السلطان'},
{id:11,category:'دعاء من خاف ظلم السلطان'},
{id:12,category:'الدعاء على العدو'},
{id:13,category:'ما يقول من خاف قوماً'},
{id:14,category:'دعاء من أصابه وسوسة في الإيمان'},
{id:15,category:'دعاء قضاء الدين'},
{id:16,category:'دعاء الوسوسة في الصلاة والقراءة'},
{id:17,category:'دعاء من استصعب عليه أمر'},
{id:18,category:'ما يقول ويفعل من أذنب ذنباً'},
{id:19,category:'دعاء طرد الشيطان ووساوسه'},
{id:20,category:'الدعاء حينما يقع ما لا يرضاه'},
{id:21,category:'تهنئة المولود له وجوابه'},
{id:22,category:'ما يعوذ به الأولاد'},
{id:23,category:'الدعاء للمريض في عيادته'},
{id:24,category:'فضل عيادة المريض'},
{id:25,category:'دعاء المريض الذي يئس من حياته'},
{id:26,category:'تلقين المحتضر'},
{id:27,category:'دعاء من أصيب بمصيبة'},
{id:28,category:'الدعاء عند إغماض الميت'},
{id:29,category:'الدعاء للميت في الصلاة عليه'},
{id:30,category:'الدعاء للفرط في الصلاة عليه'}
];