// Werd Hisn Muslim — reliable direct loader for iPhone/Safari
(function(){
let cats=[],current=null,loading=false,loadPromise=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
function inject(){const main=document.querySelector('main');if(!main)return null;let s=document.getElementById('hisn');if(!s){s=document.createElement('section');s.id='hisn';s.className='page';s.innerHTML='<div class="section-title"><h3>حصن المسلم</h3><button class="smallbtn" id="hisnBack">المزيد</button></div><div class="card"><input id="hisnSearch" style="width:100%;box-sizing:border-box;padding:12px;border:1px solid var(--line);border-radius:14px;background:var(--card);color:var(--ink)" placeholder="ابحث في أبواب حصن المسلم"></div><div class="section-title"><h3 id="hisnTitle">الأبواب</h3><span id="hisnStatus">تحميل…</span></div><div id="hisnBody"><div class="card loading">جاري تحميل حصن المسلم…</div></div>';main.appendChild(s)}const back=document.getElementById('hisnBack'),search=document.getElementById('hisnSearch');if(back&&!back.dataset.bound){back.dataset.bound='1';back.onclick=()=>{if(current){current=null;render(search?.value||'')}else window.go?.('more')}}if(search&&!search.dataset.bound){search.dataset.bound='1';search.oninput=e=>{if(!current)render(e.target.value)}}return s}
async function api(x){const r=await fetch('./api/hisn/'+x+'?v=81',{cache:'no-store',headers:{Accept:'application/json'}});if(!r.ok)throw Error('http '+r.status);const j=await r.json();if(!j.ok||!j.data)throw Error('data');return j.data}
function render(q=''){current=null;const title=document.getElementById('hisnTitle'),body=document.getElementById('hisnBody'),st=document.getElementById('hisnStatus');if(!title||!body)return;title.textContent='الأبواب';q=String(q).trim();const a=cats.filter(x=>!q||String(x.TITLE||'').includes(q));if(st)st.textContent=cats.length?cats.length+' باب':'لا توجد أبواب';body.innerHTML=a.length?'<div class="card">'+a.map(x=>'<button type="button" class="list-item" data-h="'+Number(x.ID)+'" style="width:100%;border:0;background:transparent;color:inherit;text-align:right"><div><b>'+esc(x.TITLE)+'</b><small>باب رقم '+Number(x.ID)+'</small></div><span>‹</span></button>').join('')+'</div>':'<div class="card">لا توجد نتائج.</div>';body.querySelectorAll('[data-h]').forEach(n=>n.onclick=()=>door(Number(n.dataset.h)))}
async function index(force=false){inject();if(cats.length&&!force){render(document.getElementById('hisnSearch')?.value||'');return cats}if(loadPromise&&!force)return loadPromise;loading=true;const b=document.getElementById('hisnBody'),st=document.getElementById('hisnStatus');if(b)b.innerHTML='<div class="card loading">جاري تحميل حصن المسلم…</div>';if(st)st.textContent='تحميل…';loadPromise=(async()=>{try{let j;try{j=await api('index')}catch(e){await new Promise(r=>setTimeout(r,650));j=await api('index')}cats=Array.isArray(j['العربية'])?j['العربية'].filter(x=>Number(x.ID)&&x.TITLE):[];if(!cats.length)throw Error('empty');render(document.getElementById('hisnSearch')?.value||'');return cats}catch(e){if(st)st.textContent='تعذر التحميل';if(b)b.innerHTML='<div class="card" style="text-align:center;padding:30px">تعذر تحميل أبواب حصن المسلم.<br><button class="smallbtn" id="hisnRetry" style="margin-top:12px">إعادة المحاولة</button></div>';const r=document.getElementById('hisnRetry');if(r)r.onclick=()=>index(true);throw e}finally{loading=false;loadPromise=null}})();return loadPromise}
async function door(id){current=cats.find(x=>Number(x.ID)===id);if(!current)return;const b=document.getElementById('hisnBody'),st=document.getElementById('hisnStatus'),title=document.getElementById('hisnTitle');if(title)title.textContent=current.TITLE;if(b)b.innerHTML='<div class="card loading">جاري تحميل الأذكار…</div>';if(st)st.textContent='تحميل الباب…';try{const j=await api(id),k=Object.keys(j)[0],items=Array.isArray(j[k])?j[k]:[];if(st)st.textContent=items.length+' ذكر/دعاء';if(b)b.innerHTML=items.length?items.map(x=>'<div class="card"><div style="font-size:20px;line-height:2.05">'+esc(x.ARABIC_TEXT||'')+'</div><div class="muted" style="font-size:11px;margin-top:10px">المصدر: حصن المسلم من أذكار الكتاب والسنة</div></div>').join(''):'<div class="card">لا توجد عناصر.</div>'}catch(e){if(st)st.textContent='تعذر التحميل';if(b)b.innerHTML='<div class="card" style="text-align:center;padding:30px">تعذر تحميل هذا الباب.<br><button class="smallbtn" id="doorRetry" style="margin-top:12px">إعادة المحاولة</button></div>';const r=document.getElementById('doorRetry');if(r)r.onclick=()=>door(id)}}
function activate(){inject();index().catch(()=>{})}
inject();
const priorGo=window.go;
if(typeof priorGo==='function'){window.go=function(page){const out=priorGo.apply(this,arguments);if(page==='hisn')setTimeout(activate,0);return out};try{go=window.go}catch(_){}}
window.openHisn=function(){if(typeof window.go==='function')window.go('hisn');setTimeout(activate,0)};
document.addEventListener('click',e=>{const el=e.target?.closest?.('[data-more-page="hisn"],[data-page="hisn"],[onclick*="hisn"]');if(el)setTimeout(activate,0)},true);
document.addEventListener('DOMContentLoaded',()=>{inject();if(document.getElementById('hisn')?.classList.contains('active'))activate()},{once:true});
})();