// Native Safari/iOS listening bridge. Direct user-gesture playback with resilient CDN fallback.
(function(){
  const isAppleTouch=/iPhone|iPad|iPod/i.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
  if(!isAppleTouch)return;
  const COUNTS=[7,286,200,176,120,165,206,75,129,109,123,111,43,52,99,128,111,110,98,135,112,78,118,64,77,227,93,88,69,60,34,30,73,54,45,83,182,88,75,85,54,53,89,59,37,35,38,29,18,45,60,49,62,55,78,96,29,22,24,13,14,11,11,18,12,12,30,52,52,44,28,28,20,56,40,31,50,40,46,42,29,19,36,25,22,17,19,26,30,20,15,21,11,8,8,19,5,8,8,11,11,8,3,9,5,4,7,3,6,3,5,4,5,6];
  const LEGACY={'ar.abdurrahmaansudais':'ar.sudais','ar.saoodshuraym':'ar.shuraim','ar.ahmedajamy':'ar.ajamy'};
  const NAMES={'ar.alafasy':'مشاري العفاسي','ar.sudais':'عبدالرحمن السديس','ar.mahermuaiqly':'ماهر المعيقلي','ar.husary':'محمود خليل الحصري','ar.hudhaify':'علي الحذيفي','ar.shuraim':'سعود الشريم','ar.ajamy':'أحمد العجمي','ar.abdullahbasfar':'عبدالله بصفر'};
  const EVERY={'ar.alafasy':'Alafasy_128kbps','ar.sudais':'Abdurrahmaan_As-Sudais_192kbps','ar.mahermuaiqly':'MaherAlMuaiqly128kbps','ar.husary':'Husary_128kbps','ar.hudhaify':'Hudhaify_128kbps','ar.shuraim':'Saood_ash-Shuraym_128kbps','ar.ajamy':'Ahmed_ibn_Ali_al-Ajamy_128kbps','ar.abdullahbasfar':'Abdullah_Basfar_192kbps'};
  const audio=document.createElement('audio');audio.preload='auto';audio.setAttribute('playsinline','');audio.setAttribute('webkit-playsinline','');audio.style.position='fixed';audio.style.width='1px';audio.style.height='1px';audio.style.opacity='0';audio.style.pointerEvents='none';document.body.appendChild(audio);
  let surah=1,ayah=1,candidate=0,playing=false,bound=false;
  const $=id=>document.getElementById(id),pad=n=>String(n).padStart(3,'0');
  const startOf=s=>1+COUNTS.slice(0,s-1).reduce((a,b)=>a+b,0);
  function prefs(){if(!window.state)window.state={};state.listening=state.listening||{};state.listening.reciter=LEGACY[state.listening.reciter]||state.listening.reciter||'ar.alafasy';return state.listening}
  function reciter(){return LEGACY[$('listenReciter')?.value]||$('listenReciter')?.value||prefs().reciter||'ar.alafasy'}
  function nameForSurah(s){const sel=$('listenSurah');const opt=sel?.querySelector(`option[value="${s}"]`);return(opt?.textContent||`سورة ${s}`).replace(/^\s*\d+\.\s*/, '')}
  function sources(){const g=startOf(surah)+ayah-1,r=reciter(),list=[128,64,32].map(b=>`https://cdn.islamic.network/quran/audio/${b}/${r}/${g}.mp3`);const dir=EVERY[r];if(dir)list.push(`https://everyayah.com/data/${dir}/${pad(surah)}${pad(ayah)}.mp3`);return list}
  function status(t){const x=$('listenStatus');if(x)x.textContent=t}
  function fmt(x){if(!Number.isFinite(x))return'0:00';x=Math.max(0,Math.floor(x));return`${Math.floor(x/60)}:${String(x%60).padStart(2,'0')}`}
  function render(){const sn=nameForSurah(surah),rn=NAMES[reciter()]||'القارئ';if($('listenSurahTitle'))$('listenSurahTitle').textContent=sn;if($('listenNow'))$('listenNow').textContent=`الآية ${ayah} • ${rn}`;if($('miniTitle'))$('miniTitle').textContent=sn;if($('miniSub'))$('miniSub').textContent=`الآية ${ayah} • ${rn}`;['listenPlay','miniPlay'].forEach(id=>{const b=$(id);if(b)b.textContent=playing?'⏸':'▶'});if($('listenSurah'))$('listenSurah').value=String(surah)}
  function savePos(){const p=prefs();p.lastSurah=surah;p.lastSurahName=nameForSurah(surah);p.lastAyah=ayah;try{if(typeof save==='function')save()}catch(e){}}
  async function playSource(i=0){const list=sources();candidate=Math.max(0,Math.min(list.length-1,i));audio.pause();audio.src=list[candidate];audio.playbackRate=Number(prefs().speed)||1;audio.load();try{const pr=audio.play();if(pr&&typeof pr.then==='function')await pr;playing=true;status('يعمل الآن ▶');render();$('werdMiniPlayer')?.classList.add('show');document.body.classList.add('has-mini-player')}catch(e){if(candidate<list.length-1){status('جاري تجربة مصدر صوت بديل…');return playSource(candidate+1)}playing=false;render();status('تعذر تشغيل الصوت');if(typeof toast==='function')toast('تعذر تشغيل التلاوة. تحقق من الاتصال أو جرّب قارئًا آخر')}}
  async function start(s,a=1){surah=Math.max(1,Math.min(114,Number(s)||1));ayah=Math.max(1,Math.min(COUNTS[surah-1]||1,Number(a)||1));candidate=0;savePos();render();status('بدء التلاوة…');return playSource(0)}
  async function toggle(){if(!audio.paused){audio.pause();return}if(audio.src){try{const pr=audio.play();if(pr&&typeof pr.then==='function')await pr;playing=true;status('يعمل الآن ▶');render();return}catch(e){audio.removeAttribute('src');audio.load()}}return start(Number($('listenSurah')?.value||prefs().lastSurah||1),Number(prefs().lastAyah||1))}
  async function next(){if(ayah<(COUNTS[surah-1]||1))ayah++;else{surah=surah>=114?1:surah+1;ayah=1}savePos();return playSource(0)}
  async function prev(){if(audio.currentTime>5){audio.currentTime=0;return}if(ayah>1)ayah--;else{surah=surah<=1?114:surah-1;ayah=COUNTS[surah-1]||1}savePos();return playSource(0)}
  function stopOther(e){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation()}
  function gesture(el,fn){if(!el||el.dataset.iosNativeCapture)return;el.dataset.iosNativeCapture='1';el.addEventListener('click',e=>{stopOther(e);fn()},true)}
  function bind(){const play=$('listenPlay');if(!play)return;gesture(play,toggle);gesture($('miniPlay'),toggle);gesture($('listenNext'),next);gesture($('listenPrev'),prev);gesture($('miniNext'),next);gesture($('miniPrev'),prev);const sel=$('listenSurah'),rec=$('listenReciter');if(sel&&!sel.dataset.iosNative){sel.dataset.iosNative='1';sel.addEventListener('change',e=>start(Number(e.target.value),1),true)}if(rec&&!rec.dataset.iosNative){rec.dataset.iosNative='1';rec.addEventListener('change',e=>{prefs().reciter=LEGACY[e.target.value]||e.target.value;try{if(typeof save==='function')save()}catch(x){}candidate=0;audio.pause();audio.removeAttribute('src');audio.load();playing=false;render();status('جاهز على iPhone')},true)}document.querySelectorAll('#listenSpeeds [data-speed]').forEach(b=>{if(b.dataset.iosNative)return;b.dataset.iosNative='1';b.addEventListener('click',e=>{stopOther(e);prefs().speed=Number(b.dataset.speed)||1;audio.playbackRate=prefs().speed;try{if(typeof save==='function')save()}catch(x){}document.querySelectorAll('#listenSpeeds [data-speed]').forEach(x=>x.classList.toggle('active',Number(x.dataset.speed)===prefs().speed));if(typeof toast==='function')toast(`سرعة التشغيل ${prefs().speed}×`)},true)});surah=Number(prefs().lastSurah||1);ayah=Number(prefs().lastAyah||1);window.werdListeningAudio=audio;render();status('جاهز على iPhone');bound=true}
  audio.addEventListener('play',()=>{playing=true;render()});audio.addEventListener('pause',()=>{playing=false;render()});audio.addEventListener('ended',next);audio.addEventListener('timeupdate',()=>{const d=audio.duration,c=audio.currentTime,p=Number.isFinite(d)&&d>0?c/d*100:0;if($('listenSeek'))$('listenSeek').value=String(p);if($('listenCurrent'))$('listenCurrent').textContent=fmt(c);if($('listenDuration'))$('listenDuration').textContent=fmt(d);if($('miniProgress'))$('miniProgress').style.width=p+'%'});
  const mo=new MutationObserver(()=>{if(!bound||!$('listenPlay')?.dataset.iosNativeCapture)bind()});mo.observe(document.documentElement,{childList:true,subtree:true});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(bind,0));else setTimeout(bind,0);
})();