// Native Safari/iOS listening bridge. Keeps existing UI/state, replaces only playback on Apple touch devices.
(function(){
  const isAppleTouch=/iPhone|iPad|iPod/i.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
  if(!isAppleTouch)return;
  const COUNTS=[7,286,200,176,120,165,206,75,129,109,123,111,43,52,99,128,111,110,98,135,112,78,118,64,77,227,93,88,69,60,34,30,73,54,45,83,182,88,75,85,54,53,89,59,37,35,38,29,18,45,60,49,62,55,78,96,29,22,24,13,14,11,11,18,12,12,30,52,52,44,28,28,20,56,40,31,50,40,46,42,29,19,36,25,22,17,19,26,30,20,15,21,11,8,8,19,5,8,8,11,11,8,3,9,5,4,7,3,6,3,5,4,5,6];
  const LEGACY={'ar.abdurrahmaansudais':'ar.sudais','ar.saoodshuraym':'ar.shuraim','ar.ahmedajamy':'ar.ajamy'};
  const NAMES={'ar.alafasy':'مشاري العفاسي','ar.sudais':'عبدالرحمن السديس','ar.mahermuaiqly':'ماهر المعيقلي','ar.husary':'محمود خليل الحصري','ar.hudhaify':'علي الحذيفي','ar.shuraim':'سعود الشريم','ar.ajamy':'أحمد العجمي','ar.abdullahbasfar':'عبدالله بصفر'};
  const audio=document.createElement('audio');audio.preload='metadata';audio.setAttribute('playsinline','');audio.setAttribute('webkit-playsinline','');audio.style.display='none';document.body.appendChild(audio);
  let surah=1,ayah=1,candidate=0,playing=false;
  const $=id=>document.getElementById(id);
  const startOf=s=>1+COUNTS.slice(0,s-1).reduce((a,b)=>a+b,0);
  function prefs(){state.listening=state.listening||{};state.listening.reciter=LEGACY[state.listening.reciter]||state.listening.reciter||'ar.alafasy';return state.listening}
  function reciter(){return $('listenReciter')?.value||prefs().reciter||'ar.alafasy'}
  function nameForSurah(s){const list=(Array.isArray(window.surahs)&&window.surahs.length)?window.surahs:(window.fallbackSurahs||[]);return list.find(x=>Number(x.number)===Number(s))?.name||`سورة ${s}`}
  function candidates(){const g=startOf(surah)+ayah-1,r=reciter();return[128,64,32].map(b=>`https://cdn.islamic.network/quran/audio/${b}/${r}/${g}.mp3`)}
  function status(t){const x=$('listenStatus');if(x)x.textContent=t}
  function fmt(x){if(!Number.isFinite(x))return'0:00';x=Math.max(0,Math.floor(x));return`${Math.floor(x/60)}:${String(x%60).padStart(2,'0')}`}
  function render(){const sn=nameForSurah(surah),rn=NAMES[reciter()]||'القارئ';if($('listenSurahTitle'))$('listenSurahTitle').textContent=sn;if($('listenNow'))$('listenNow').textContent=`الآية ${ayah} • ${rn}`;if($('miniTitle'))$('miniTitle').textContent=sn;if($('miniSub'))$('miniSub').textContent=`الآية ${ayah} • ${rn}`;['listenPlay','miniPlay'].forEach(id=>{const b=$(id);if(b)b.textContent=playing?'⏸':'▶'});if($('listenSurah'))$('listenSurah').value=String(surah)}
  async function playSource(i=0){
    const list=candidates();candidate=Math.max(0,Math.min(list.length-1,i));audio.pause();audio.src=list[candidate];audio.playbackRate=Number(prefs().speed)||1;
    try{await audio.play();playing=true;status('يعمل الآن ▶');render();document.getElementById('werdMiniPlayer')?.classList.add('show');document.body.classList.add('has-mini-player')}
    catch(e){console.warn('Werd iOS native audio',e,list[candidate]);if(candidate<list.length-1){status('تجربة جودة صوت بديلة…');return playSource(candidate+1)}playing=false;render();status('تعذر تشغيل الصوت');if(typeof toast==='function')toast(e?.name==='NotAllowedError'?'اضغط تشغيل مرة أخرى':'تعذر تشغيل التلاوة. جرّب قارئًا آخر أو تحقق من الاتصال')}
  }
  function savePos(){const p=prefs();p.lastSurah=surah;p.lastSurahName=nameForSurah(surah);p.lastAyah=ayah;if(typeof save==='function')save()}
  async function start(s,a=1){surah=Math.max(1,Math.min(114,Number(s)||1));ayah=Math.max(1,Math.min(COUNTS[surah-1]||1,Number(a)||1));candidate=0;savePos();render();status('بدء التلاوة…');return playSource(0)}
  async function toggle(){if(audio.src&&!audio.paused){audio.pause();return}if(audio.src&&audio.paused){try{await audio.play();playing=true;status('يعمل الآن ▶');render();return}catch(e){return playSource(candidate)}}const s=Number($('listenSurah')?.value||prefs().lastSurah||1),a=Number(prefs().lastAyah||1);return start(s,a)}
  async function next(){if(ayah<(COUNTS[surah-1]||1))ayah++;else{surah=surah>=114?1:surah+1;ayah=1}savePos();return playSource(0)}
  async function prev(){if(audio.currentTime>5){audio.currentTime=0;return}if(ayah>1)ayah--;else{surah=surah<=1?114:surah-1;ayah=COUNTS[surah-1]||1}savePos();return playSource(0)}
  function bind(){const play=$('listenPlay'),mini=$('miniPlay'),n=$('listenNext'),p=$('listenPrev'),mn=$('miniNext'),mp=$('miniPrev'),sel=$('listenSurah'),rec=$('listenReciter');if(!play||play.dataset.iosNative)return;play.dataset.iosNative='1';play.onclick=toggle;if(mini)mini.onclick=toggle;if(n)n.onclick=next;if(p)p.onclick=prev;if(mn)mn.onclick=next;if(mp)mp.onclick=prev;if(sel)sel.onchange=e=>start(Number(e.target.value),1);if(rec)rec.onchange=e=>{prefs().reciter=e.target.value;if(typeof save==='function')save();candidate=0;audio.pause();audio.removeAttribute('src');audio.load();playing=false;render();status('جاهز')};document.querySelectorAll('#listenSpeeds [data-speed]').forEach(b=>b.onclick=()=>{prefs().speed=Number(b.dataset.speed)||1;audio.playbackRate=prefs().speed;if(typeof save==='function')save();document.querySelectorAll('#listenSpeeds [data-speed]').forEach(x=>x.classList.toggle('active',Number(x.dataset.speed)===prefs().speed));if(typeof toast==='function')toast(`سرعة التشغيل ${prefs().speed}×`)});surah=Number(prefs().lastSurah||1);ayah=Number(prefs().lastAyah||1);window.werdListeningAudio=audio;render();status('جاهز على iPhone')}
  audio.addEventListener('play',()=>{playing=true;render()});audio.addEventListener('pause',()=>{playing=false;render()});audio.addEventListener('ended',next);audio.addEventListener('timeupdate',()=>{const d=audio.duration,c=audio.currentTime,p=Number.isFinite(d)&&d>0?c/d*100:0;if($('listenSeek'))$('listenSeek').value=String(p);if($('listenCurrent'))$('listenCurrent').textContent=fmt(c);if($('listenDuration'))$('listenDuration').textContent=fmt(d);if($('miniProgress'))$('miniProgress').style.width=p+'%'});audio.addEventListener('error',()=>{if(candidate<2)playSource(candidate+1);else{playing=false;status('تعذر تشغيل الصوت');render()}});
  const mo=new MutationObserver(()=>bind());mo.observe(document.documentElement,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(bind,0));else setTimeout(bind,0);
})();