// Advanced memorization and revision mode for Werd
(function(){
  const COUNTS=[7,286,200,176,120,165,206,75,129,109,123,111,43,52,99,128,111,110,98,135,112,78,118,64,77,227,93,88,69,60,34,30,73,54,45,83,182,88,75,85,54,53,89,59,37,35,38,29,18,45,60,49,62,55,78,96,29,22,24,13,14,11,11,18,12,12,30,52,52,44,28,28,20,56,40,31,50,40,46,42,29,19,36,25,22,17,19,26,30,20,15,21,11,8,8,19,5,8,8,11,11,8,3,9,5,4,7,3,6,3,5,4,5,6];
  const RECITERS=[['ar.alafasy','مشاري العفاسي'],['ar.sudais','عبدالرحمن السديس'],['ar.mahermuaiqly','ماهر المعيقلي'],['ar.husary','محمود خليل الحصري'],['ar.hudhaify','علي الحذيفي'],['ar.shuraim','سعود الشريم'],['ar.ajamy','أحمد العجمي'],['ar.abdullahbasfar','عبدالله بصفر']];
  const LEGACY={'ar.abdurrahmaansudais':'ar.sudais','ar.saoodshuraym':'ar.shuraim','ar.ahmedajamy':'ar.ajamy'};
  const CDN='https://cdn.islamic.network/quran/audio';
  const BITRATES=[128,64,192,48,40,32];
  const audio=new Audio();audio.preload='metadata';audio.playsInline=true;
  let running=false,paused=false,timer=null,session=[],pos=0,repeatNo=1,roundNo=1,candidate=0;

  function prefs(){
    if(!state.memorization||typeof state.memorization!=='object'||Array.isArray(state.memorization))state.memorization={};
    state.memorization={surah:1,fromAyah:1,toAyah:7,repeats:3,gap:2,mode:'ayah',reciter:'ar.alafasy',lastAyah:1,...state.memorization};
    state.memorization.reciter=LEGACY[state.memorization.reciter]||state.memorization.reciter;
    if(!RECITERS.some(x=>x[0]===state.memorization.reciter))state.memorization.reciter='ar.alafasy';
    if(!['ayah','range'].includes(state.memorization.mode))state.memorization.mode='ayah';
    return state.memorization;
  }
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function globalStart(s){let n=1;for(let i=0;i<s-1;i++)n+=COUNTS[i]||0;return n}
  function surahName(n){const list=(Array.isArray(window.surahs)&&surahs.length)?surahs:(window.fallbackSurahs||[]);return list.find(x=>Number(x.number)===Number(n))?.name||`سورة ${n}`}
  function candidates(global,reciter){return BITRATES.map(b=>`${CDN}/${b}/${reciter}/${global}.mp3`)}
  function list(){const l=(Array.isArray(window.surahs)&&surahs.length)?surahs:(window.fallbackSurahs||[]);if(l.length)return l;return Array.from({length:114},(_,i)=>({number:i+1,name:`سورة ${i+1}`,numberOfAyahs:COUNTS[i]}))}
  function stopTimer(){if(timer)clearTimeout(timer);timer=null}

  function injectStyles(){if(document.getElementById('werdMemStyle'))return;const s=document.createElement('style');s.id='werdMemStyle';s.textContent=`
    .mem-hero{background:linear-gradient(145deg,var(--green),#164d3d);color:white;border-radius:24px;padding:20px;text-align:center}.mem-hero .muted{color:rgba(255,255,255,.72)}.mem-now{font-size:28px;font-weight:900;margin:10px 0 4px}.mem-progress{height:8px;background:rgba(255,255,255,.18);border-radius:99px;overflow:hidden;margin-top:13px}.mem-progress span{display:block;height:100%;width:0;background:#f0d39b;transition:width .2s}
    .mem-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.mem-field label{display:block;font-size:11px;color:var(--muted);margin-bottom:5px}.mem-field select,.mem-field input{width:100%;border:1px solid var(--line);background:var(--card);color:var(--ink);border-radius:13px;padding:11px}.mem-mode{display:grid;grid-template-columns:1fr 1fr;gap:8px}.mem-mode button.active{background:var(--green);color:#fff;border-color:var(--green)}.mem-controls{display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px}.mem-tip{font-size:11px;line-height:1.8;color:var(--muted)}.mem-wait{animation:memPulse 1s infinite alternate}@keyframes memPulse{to{opacity:.45}}@media(max-width:380px){.mem-grid{grid-template-columns:1fr}.mem-controls{grid-template-columns:1fr 1fr}.mem-controls #memStart{grid-column:1/-1}}
  `;document.head.appendChild(s)}

  function inject(){injectStyles();prefs();const main=document.querySelector('main');if(!main)return;
    if(!document.getElementById('memorization')){const sec=document.createElement('section');sec.className='page';sec.id='memorization';sec.innerHTML=`
      <div class="section-title"><h3>الحفظ والمراجعة</h3><button class="smallbtn" id="memBack">المصحف</button></div>
      <div class="mem-hero"><div class="muted" id="memState">جاهز للجلسة</div><div class="mem-now" id="memNow">اختر النطاق</div><div id="memDetail">تكرار منظم يساعدك على التلقين والمراجعة</div><div class="mem-progress"><span id="memProgress"></span></div></div>
      <div class="card" style="margin-top:10px"><div class="mem-field"><label>السورة</label><select id="memSurah"></select></div><div class="mem-grid" style="margin-top:9px"><div class="mem-field"><label>من الآية</label><input id="memFrom" type="number" min="1" inputmode="numeric"></div><div class="mem-field"><label>إلى الآية</label><input id="memTo" type="number" min="1" inputmode="numeric"></div></div></div>
      <div class="card" style="margin-top:10px"><b>طريقة الجلسة</b><div class="mem-mode" style="margin-top:9px"><button class="smallbtn" data-mem-mode="ayah">تلقين كل آية</button><button class="smallbtn" data-mem-mode="range">مراجعة النطاق</button></div><div class="mem-grid" style="margin-top:10px"><div class="mem-field"><label>عدد التكرارات / الجولات</label><select id="memRepeats"><option value="1">مرة واحدة</option><option value="3">3 مرات</option><option value="5">5 مرات</option><option value="10">10 مرات</option></select></div><div class="mem-field"><label>التوقف بين التكرارات</label><select id="memGap"><option value="0">بدون توقف</option><option value="1">1 ثانية</option><option value="2">2 ثانية</option><option value="3">3 ثوانٍ</option><option value="5">5 ثوانٍ</option><option value="10">10 ثوانٍ</option></select></div></div><div class="mem-field" style="margin-top:9px"><label>القارئ</label><select id="memReciter">${RECITERS.map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('')}</select></div></div>
      <div class="card" style="margin-top:10px"><div class="mem-controls"><button class="primary" id="memStart" style="margin:0">▶ بدء الجلسة</button><button class="smallbtn" id="memPause">⏸ إيقاف مؤقت</button><button class="smallbtn" id="memStop">■ إنهاء</button></div><div class="mem-tip" style="margin-top:10px">في «تلقين كل آية» تتكرر الآية بالعدد المحدد قبل الانتقال إلى التالية. في «مراجعة النطاق» يُقرأ النطاق كاملًا ثم يبدأ من أوله في الجولة التالية.</div></div>`;main.appendChild(sec)}
    addEntries();wire();syncUI();decorateReader();
  }

  function addEntries(){
    const mg=document.querySelector('#more .more-grid');if(mg&&!document.getElementById('moreMemTile')){const b=document.createElement('button');b.className='more-tile';b.id='moreMemTile';b.innerHTML='<span class="mi">🧠</span><b>الحفظ والمراجعة</b><small>تلقين وتكرار نطاق الآيات</small>';b.onclick=()=>openMem();mg.insertBefore(b,mg.firstChild)}
    const lh=document.querySelector('#listening .section-title');if(lh&&!document.getElementById('listenMemBtn')){const b=document.createElement('button');b.className='smallbtn';b.id='listenMemBtn';b.textContent='🧠 الحفظ';b.onclick=()=>openMem(state.listening?.lastSurah,state.listening?.lastAyah);lh.appendChild(b)}
    const rp=document.getElementById('werdReaderPanel');if(rp&&!document.getElementById('readerMemBtn')){const b=document.createElement('button');b.className='smallbtn';b.id='readerMemBtn';b.textContent='🧠 وضع الحفظ';b.onclick=()=>openMem(Number(state.lastSurah?.number||state.lastSurah||1),1);rp.appendChild(b)}
  }
  function decorateReader(){document.querySelectorAll('#ayahs .ayah').forEach(node=>{const tools=node.querySelector('.reader-tools');if(!tools||tools.querySelector('.mem-ayah-btn'))return;const ay=Number(node.querySelector('.an')?.textContent||0);if(!ay)return;const b=document.createElement('button');b.className='smallbtn mem-ayah-btn';b.textContent='🧠 حفظ';b.onclick=()=>openMem(Number(state.lastSurah?.number||state.lastSurah||1),ay);tools.appendChild(b)})}

  function wire(){const $=id=>document.getElementById(id);$('memBack').onclick=()=>{stopSession(false);go('quran')};$('memSurah').onchange=()=>{const p=prefs();p.surah=Number($('memSurah').value);p.fromAyah=1;p.toAyah=COUNTS[p.surah-1];save();syncUI()};for(const id of ['memFrom','memTo','memRepeats','memGap','memReciter'])$(id).onchange=readUI;document.querySelectorAll('[data-mem-mode]').forEach(b=>b.onclick=()=>{prefs().mode=b.dataset.memMode;save();syncUI()});$('memStart').onclick=startSession;$('memPause').onclick=pauseResume;$('memStop').onclick=()=>stopSession(true);const obs=new MutationObserver(()=>decorateReader());const ay=document.getElementById('ayahs');if(ay)obs.observe(ay,{childList:true,subtree:true})}
  function readUI(){const p=prefs(),max=COUNTS[Number(document.getElementById('memSurah').value)-1]||1;p.surah=Number(document.getElementById('memSurah').value)||1;p.fromAyah=Math.max(1,Math.min(max,Number(document.getElementById('memFrom').value)||1));p.toAyah=Math.max(p.fromAyah,Math.min(max,Number(document.getElementById('memTo').value)||p.fromAyah));p.repeats=Number(document.getElementById('memRepeats').value)||3;p.gap=Number(document.getElementById('memGap').value)||0;p.reciter=LEGACY[document.getElementById('memReciter').value]||document.getElementById('memReciter').value;save();syncUI()}
  function syncUI(){const p=prefs(),s=document.getElementById('memSurah');if(!s)return;s.innerHTML=list().map(x=>`<option value="${x.number}">${x.number}. ${esc(x.name)}</option>`).join('');s.value=String(p.surah);const max=COUNTS[p.surah-1]||1;p.fromAyah=Math.max(1,Math.min(max,Number(p.fromAyah)||1));p.toAyah=Math.max(p.fromAyah,Math.min(max,Number(p.toAyah)||max));document.getElementById('memFrom').max=max;document.getElementById('memTo').max=max;document.getElementById('memFrom').value=p.fromAyah;document.getElementById('memTo').value=p.toAyah;document.getElementById('memRepeats').value=String(p.repeats);document.getElementById('memGap').value=String(p.gap);document.getElementById('memReciter').value=p.reciter;document.querySelectorAll('[data-mem-mode]').forEach(b=>b.classList.toggle('active',b.dataset.memMode===p.mode))}
  function openMem(surah,ayah){const p=prefs();if(surah){p.surah=Math.max(1,Math.min(114,Number(surah)||1));const max=COUNTS[p.surah-1];if(ayah){p.fromAyah=Math.max(1,Math.min(max,Number(ayah)||1));p.toAyah=p.fromAyah}else{p.fromAyah=Math.min(p.fromAyah,max);p.toAyah=Math.max(p.fromAyah,Math.min(p.toAyah,max))}save()}syncUI();go('memorization')}
  window.openWerdMemorization=openMem;

  function makeSession(){const p=prefs(),start=globalStart(p.surah);session=[];for(let a=p.fromAyah;a<=p.toAyah;a++)session.push({surah:p.surah,surahName:surahName(p.surah),ayah:a,global:start+a-1,candidates:candidates(start+a-1,p.reciter)});return session}
  async function startSession(){readUI();stopTimer();audio.pause();audio.removeAttribute('src');makeSession();if(!session.length)return toast('حدد نطاقًا صحيحًا');running=true;paused=false;pos=0;repeatNo=1;roundNo=1;candidate=0;await playCurrent()}
  async function playCurrent(){if(!running||paused)return;const t=session[pos];if(!t)return finish();candidate=0;prefs().lastAyah=t.ayah;save();updateStatus('تشغيل',t);await tryCandidate(t)}
  async function tryCandidate(t){if(!running||paused)return;const list=t.candidates||[];if(candidate>=list.length){toast('تعذر تشغيل هذه الآية');return advanceAfterAyah()}audio.src=list[candidate];audio.playbackRate=Number(state.listening?.speed)||1;try{await audio.play();updateStatus('يعمل الآن',t)}catch(e){candidate++;tryCandidate(t)}}
  function waitThen(fn,label){const gap=Number(prefs().gap)||0;if(!gap)return fn();updateStatus(`توقف ${gap} ث`,session[pos],true);timer=setTimeout(()=>{timer=null;if(running&&!paused)fn()},gap*1000)}
  function ended(){if(!running)return;const p=prefs();if(p.mode==='ayah'){if(repeatNo<p.repeats){repeatNo++;return waitThen(playCurrent)}repeatNo=1;return advanceAfterAyah()}return advanceRangeMode()}
  function advanceAfterAyah(){if(pos<session.length-1){pos++;return waitThen(playCurrent)}finish()}
  function advanceRangeMode(){const p=prefs();if(pos<session.length-1){pos++;return waitThen(playCurrent)}if(roundNo<p.repeats){roundNo++;pos=0;return waitThen(playCurrent)}finish()}
  function pauseResume(){if(!running)return toast('ابدأ جلسة الحفظ أولًا');if(!paused){paused=true;stopTimer();audio.pause();document.getElementById('memPause').textContent='▶ متابعة';document.getElementById('memState').textContent='متوقف مؤقتًا'}else{paused=false;document.getElementById('memPause').textContent='⏸ إيقاف مؤقت';playCurrent()}}
  function stopSession(notify){running=false;paused=false;stopTimer();audio.pause();audio.removeAttribute('src');document.getElementById('memPause')&&(document.getElementById('memPause').textContent='⏸ إيقاف مؤقت');updateIdle('تم إنهاء الجلسة');if(notify)toast('تم إنهاء جلسة الحفظ')}
  function finish(){running=false;paused=false;stopTimer();audio.pause();updateIdle('اكتملت الجلسة ✓');toast('أحسنت، اكتملت جلسة الحفظ ✓')}
  function updateIdle(txt){const a=document.getElementById('memState'),b=document.getElementById('memNow'),d=document.getElementById('memDetail'),bar=document.getElementById('memProgress');if(a)a.textContent=txt;if(b)b.textContent='جلسة الحفظ';if(d)d.textContent='يمكنك تعديل النطاق وبدء جلسة جديدة';if(bar)bar.style.width='100%'}
  function updateStatus(status,t,waiting=false){const p=prefs(),total=p.mode==='ayah'?session.length*p.repeats:session.length*p.repeats;const completed=p.mode==='ayah'?(pos*p.repeats+(repeatNo-1)):( (roundNo-1)*session.length+pos );const pct=Math.max(0,Math.min(100,Math.round(completed/Math.max(1,total)*100)));const a=document.getElementById('memState'),b=document.getElementById('memNow'),d=document.getElementById('memDetail'),bar=document.getElementById('memProgress');if(a){a.textContent=status;a.classList.toggle('mem-wait',waiting)}if(b)b.textContent=`${t.surahName} • الآية ${t.ayah}`;if(d)d.textContent=p.mode==='ayah'?`التكرار ${repeatNo} من ${p.repeats}`:`الجولة ${roundNo} من ${p.repeats} • الآية ${pos+1} من ${session.length}`;if(bar)bar.style.width=pct+'%'}

  audio.addEventListener('ended',ended);audio.addEventListener('error',()=>{if(!running)return;candidate++;tryCandidate(session[pos])});
  const baseRender=typeof renderState==='function'?renderState:null;if(baseRender)renderState=function(){baseRender();prefs();syncUI();addEntries();decorateReader()};
  inject();
})();