// Smart memorization self-test for Werd
(function(){
  const COUNTS=[7,286,200,176,120,165,206,75,129,109,123,111,43,52,99,128,111,110,98,135,112,78,118,64,77,227,93,88,69,60,34,30,73,54,45,83,182,88,75,85,54,53,89,59,37,35,38,29,18,45,60,49,62,55,78,96,29,22,24,13,14,11,11,18,12,12,30,52,52,44,28,28,20,56,40,31,50,40,46,42,29,19,36,25,22,17,19,26,30,20,15,21,11,8,8,19,5,8,8,19,5,8,8,11,11,8,3,9,5,4,7,3,6,3,5,4,5,6];
  const INTERVALS={1:1,2:3,3:7,4:14,5:30};
  let session=[],index=0,revealed=false,rated=false,loading=false,scope='due';
  let sessionStats={again:0,hard:0,good:0,easy:0};

  function tracker(){
    if(!state.memorizationTracker||typeof state.memorizationTracker!=='object'||Array.isArray(state.memorizationTracker))state.memorizationTracker={};
    state.memorizationTracker={version:1,items:{},history:[],settings:{reminderEnabled:true,reminderTime:'19:30',dailyGoal:5},testHistory:[],...state.memorizationTracker};
    if(!state.memorizationTracker.items||typeof state.memorizationTracker.items!=='object'||Array.isArray(state.memorizationTracker.items))state.memorizationTracker.items={};
    if(!Array.isArray(state.memorizationTracker.history))state.memorizationTracker.history=[];
    if(!Array.isArray(state.memorizationTracker.testHistory))state.memorizationTracker.testHistory=[];
    return state.memorizationTracker;
  }
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function localDate(d=new Date()){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return`${y}-${m}-${day}`}
  function addDays(date,days){const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()+Number(days||0));return localDate(d)}
  function clamp(n){return Math.max(1,Math.min(5,Number(n)||1))}
  function globalStart(s){let n=1;for(let i=0;i<s-1;i++)n+=COUNTS[i]||0;return n}
  function surahName(n){const list=(Array.isArray(window.surahs)&&surahs.length)?surahs:(window.fallbackSurahs||[]);return list.find(x=>Number(x.number)===Number(n))?.name||`سورة ${n}`}
  function allItems(){return Object.values(tracker().items).filter(x=>x&&!x.archived)}
  function dueItems(){const t=localDate();return allItems().filter(x=>String(x.nextReview||t)<=t)}
  function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}

  function injectStyles(){if(document.getElementById('werdMemTestStyle'))return;const s=document.createElement('style');s.id='werdMemTestStyle';s.textContent=`
    .mtest-hero{background:linear-gradient(145deg,var(--green),#173f34);color:#fff;border-radius:24px;padding:20px;text-align:center}.mtest-hero small{opacity:.72}.mtest-prompt{font-size:19px;font-weight:900;line-height:1.8;margin:12px 0}.mtest-progress{height:7px;background:rgba(255,255,255,.16);border-radius:99px;overflow:hidden;margin-top:14px}.mtest-progress span{display:block;height:100%;background:#f0d39b;width:0;transition:width .25s}.mtest-config{display:grid;grid-template-columns:1fr 1fr;gap:9px}.mtest-config label{display:block;font-size:10px;color:var(--muted);margin-bottom:5px}.mtest-config select{width:100%;padding:10px;border:1px solid var(--line);border-radius:13px;background:var(--card);color:var(--ink)}.mtest-scope{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.mtest-scope button.active{background:var(--green);color:white;border-color:var(--green)}.mtest-reveal{min-height:152px;border:1px dashed var(--line);border-radius:19px;padding:16px;display:flex;align-items:center;justify-content:center;text-align:center;line-height:2.15;font-size:20px}.mtest-hidden{color:var(--muted);font-size:12px}.mtest-rate{display:grid;grid-template-columns:repeat(4,1fr);gap:7px}.mtest-rate button{padding:10px 5px;font-size:10px}.mtest-rate button:disabled{opacity:.42}.mtest-summary-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:7px}.mtest-stat{background:var(--sage);border-radius:15px;padding:10px 4px;text-align:center}.mtest-stat b{font-size:19px;display:block}.mtest-stat small{font-size:8px;color:var(--muted)}.mtest-good{border-inline-start:3px solid #4e7d68}.mtest-hard{border-inline-start:3px solid #bd8d54}@media(max-width:390px){.mtest-config{grid-template-columns:1fr}.mtest-rate{grid-template-columns:1fr 1fr}.mtest-summary-grid{grid-template-columns:1fr 1fr}.mtest-scope{grid-template-columns:1fr}}
  `;document.head.appendChild(s)}

  function inject(){
    injectStyles();tracker();const main=document.querySelector('main');if(!main)return;
    if(!document.getElementById('memorizationTest')){const sec=document.createElement('section');sec.className='page';sec.id='memorizationTest';sec.innerHTML=`
      <div class="section-title"><h3>اختبار الحفظ</h3><button class="smallbtn" id="mtestBack">متابعة الحفظ</button></div>
      <div class="mtest-hero"><small id="mtestHeroLabel">اختبر حفظك بدون النظر إلى النص</small><div class="mtest-prompt" id="mtestPrompt">اختر نوع الاختبار ثم ابدأ</div><div id="mtestCounter">—</div><div class="mtest-progress"><span id="mtestProgress"></span></div></div>
      <div class="card" id="mtestSetup" style="margin-top:10px"><b>إعداد الاختبار</b><div class="mtest-scope" style="margin-top:10px"><button class="smallbtn active" data-mtest-scope="due">مستحق اليوم</button><button class="smallbtn" data-mtest-scope="all">كل المحفوظ</button><button class="smallbtn" data-mtest-scope="surah">سورة محددة</button></div><div class="mtest-config" style="margin-top:10px"><div><label>عدد الآيات</label><select id="mtestCount"><option value="5">5 آيات</option><option value="10" selected>10 آيات</option><option value="20">20 آية</option></select></div><div><label>السورة</label><select id="mtestSurah" disabled></select></div></div><button class="primary" id="mtestStart" style="margin-top:12px;width:100%">ابدأ الاختبار</button><div class="muted" id="mtestAvailable" style="margin-top:8px;text-align:center">—</div></div>
      <div class="card" id="mtestSession" style="display:none;margin-top:10px"><div class="mtest-reveal" id="mtestReveal"><div class="mtest-hidden">اقرأ الآية من حفظك أولًا.<br>النص مخفي حتى تطلب كشفه.</div></div><div class="row" style="margin-top:10px"><button class="secondary" id="mtestShow" style="margin:0;flex:1">👁 كشف الآية</button><button class="smallbtn" id="mtestOpenMem">🧠 تلقين</button></div><div style="margin-top:13px"><b>كيف كانت إجابتك؟</b><div class="mtest-rate" style="margin-top:8px"><button class="smallbtn" data-mtest-rate="again">↺ أعدها</button><button class="smallbtn" data-mtest-rate="hard">◔ صعب</button><button class="smallbtn" data-mtest-rate="good">✓ جيد</button><button class="smallbtn" data-mtest-rate="easy">★ متقن</button></div></div><button class="primary" id="mtestNext" disabled style="width:100%;margin-top:11px">التالي</button></div>
      <div class="card" id="mtestSummary" style="display:none;margin-top:10px"><div style="text-align:center"><div style="font-size:34px">🏁</div><h3 style="margin:5px 0">اكتمل الاختبار</h3><div class="muted" id="mtestSummaryText">—</div></div><div class="mtest-summary-grid" style="margin-top:13px"><div class="mtest-stat"><b id="mtestSAgain">0</b><small>أعدها</small></div><div class="mtest-stat"><b id="mtestSHard">0</b><small>صعب</small></div><div class="mtest-stat"><b id="mtestSGood">0</b><small>جيد</small></div><div class="mtest-stat"><b id="mtestSEasy">0</b><small>متقن</small></div></div><div class="row" style="margin-top:12px"><button class="primary" id="mtestAgain" style="margin:0;flex:1">اختبار جديد</button><button class="secondary" id="mtestTracker" style="margin:0;flex:1">متابعة الحفظ</button></div></div>`;main.appendChild(sec)}
    addEntries();wire();renderSetup();
  }

  function addEntries(){
    const mg=document.querySelector('#more .more-grid');if(mg&&!document.getElementById('moreMemTestTile')){const b=document.createElement('button');b.className='more-tile';b.id='moreMemTestTile';b.innerHTML='<span class="mi">🎯</span><b>اختبار الحفظ</b><small>اختبر نفسك ثم حدّث مستوى الإتقان</small>';b.onclick=openTest;mg.insertBefore(b,mg.firstChild)}
    const tr=document.querySelector('#memorizationTracker .section-title');if(tr&&!document.getElementById('mtestTrackerEntry')){const b=document.createElement('button');b.className='smallbtn';b.id='mtestTrackerEntry';b.textContent='🎯 اختبار';b.onclick=openTest;tr.appendChild(b)}
    const mem=document.querySelector('#memorization .section-title');if(mem&&!document.getElementById('mtestMemEntry')){const b=document.createElement('button');b.className='smallbtn';b.id='mtestMemEntry';b.textContent='🎯 اختبرني';b.onclick=openTest;mem.appendChild(b)}
  }

  function wire(){const $=id=>document.getElementById(id);$('mtestBack').onclick=openTracker;$('mtestStart').onclick=startTest;$('mtestShow').onclick=revealAyah;$('mtestNext').onclick=next;$('mtestAgain').onclick=resetTest;$('mtestTracker').onclick=openTracker;$('mtestOpenMem').onclick=()=>{const x=session[index];if(x&&typeof window.openWerdMemorization==='function')window.openWerdMemorization(x.surah,x.ayah)};$('mtestSurah').onchange=renderSetup;document.querySelectorAll('[data-mtest-scope]').forEach(b=>b.onclick=()=>{scope=b.dataset.mtestScope;document.querySelectorAll('[data-mtest-scope]').forEach(x=>x.classList.toggle('active',x.dataset.mtestScope===scope));$('mtestSurah').disabled=scope!=='surah';renderSetup()});document.querySelectorAll('[data-mtest-rate]').forEach(b=>b.onclick=()=>rateCurrent(b.dataset.mtestRate))}
  function openTracker(){if(typeof window.openWerdMemorizationTracker==='function')window.openWerdMemorizationTracker();else go('memorizationTracker')}
  function openTest(){resetTest(false);go('memorizationTest');renderSetup()} window.openWerdMemorizationTest=openTest;

  function candidates(){let a=scope==='due'?dueItems():allItems();if(scope==='surah'){const s=Number(document.getElementById('mtestSurah')?.value||1);a=a.filter(x=>Number(x.surah)===s)}return a}
  function availableSurahs(){const map=new Map();allItems().forEach(x=>map.set(Number(x.surah),x.surahName||surahName(x.surah)));return[...map.entries()].sort((a,b)=>a[0]-b[0])}
  function renderSetup(){const sel=document.getElementById('mtestSurah');if(!sel)return;const prior=sel.value;const ss=availableSurahs();sel.innerHTML=ss.length?ss.map(([n,name])=>`<option value="${n}">${n}. ${esc(name)}</option>`).join(''):'<option value="1">لا توجد سور محفوظة</option>';if(prior&&ss.some(x=>String(x[0])===prior))sel.value=prior;const n=candidates().length;document.getElementById('mtestAvailable').textContent=scope==='due'?`${n} آية مستحقة للمراجعة اليوم`:`${n} آية متاحة للاختبار`;document.getElementById('mtestStart').disabled=!n}

  function startTest(){const pool=candidates();if(!pool.length)return toast(scope==='due'?'لا توجد آيات مستحقة اليوم':'لا توجد آيات في هذا النطاق');const count=Math.min(pool.length,Number(document.getElementById('mtestCount').value)||10);session=shuffle(pool.slice()).slice(0,count);index=0;sessionStats={again:0,hard:0,good:0,easy:0};document.getElementById('mtestSetup').style.display='none';document.getElementById('mtestSummary').style.display='none';document.getElementById('mtestSession').style.display='block';showQuestion()}
  function showQuestion(){const x=session[index];if(!x)return finish();revealed=false;rated=false;loading=false;document.getElementById('mtestHeroLabel').textContent='اقرأ من حفظك';document.getElementById('mtestPrompt').textContent=`${x.surahName||surahName(x.surah)} • الآية ${x.ayah}`;document.getElementById('mtestCounter').textContent=`${index+1} من ${session.length}`;document.getElementById('mtestProgress').style.width=`${Math.round(index/session.length*100)}%`;document.getElementById('mtestReveal').innerHTML='<div class="mtest-hidden">اقرأ الآية من حفظك أولًا.<br>ثم اكشف النص للمقارنة.</div>';document.getElementById('mtestShow').disabled=false;document.getElementById('mtestShow').textContent='👁 كشف الآية';document.getElementById('mtestNext').disabled=true;document.getElementById('mtestNext').textContent=index===session.length-1?'إنهاء الاختبار':'التالي';document.querySelectorAll('[data-mtest-rate]').forEach(b=>b.disabled=false)}

  async function revealAyah(){if(revealed||loading)return;const x=session[index];if(!x)return;loading=true;const btn=document.getElementById('mtestShow');btn.disabled=true;btn.textContent='جاري تحميل النص…';try{const global=Number(x.global)||globalStart(Number(x.surah))+Number(x.ayah)-1;const r=await fetch(`${API_QURAN}/ayah/${global}/quran-uthmani`);if(!r.ok)throw new Error('network');const j=await r.json(),text=j?.data?.text;if(!text)throw new Error('missing');document.getElementById('mtestReveal').innerHTML=`<div><div style="font-family:serif;font-size:22px;line-height:2.25">${esc(text)}</div><div class="muted" style="margin-top:9px">${esc(x.surahName||surahName(x.surah))} • الآية ${x.ayah}</div></div>`;revealed=true;btn.textContent='✓ تم كشف الآية'}catch(e){console.error(e);btn.disabled=false;btn.textContent='إعادة محاولة كشف الآية';toast('تعذر تحميل نص الآية الآن')}finally{loading=false}}

  function rateCurrent(rating){if(rated)return;const x=session[index],t=tracker(),id=x?.id||`${x?.surah}:${x?.ayah}`,item=t.items[id];if(!item)return toast('تعذر العثور على بيانات الآية');const before=clamp(item.mastery);let after=before,days=1,success=true;if(rating==='again'){after=1;days=1;success=false;item.lapses=(Number(item.lapses)||0)+1}else if(rating==='hard'){after=Math.max(1,before);days=Math.max(1,Math.ceil((INTERVALS[after]||1)/2))}else if(rating==='good'){after=Math.min(5,before+1);days=INTERVALS[after]||7}else if(rating==='easy'){after=Math.min(5,before+2);days=Math.max(INTERVALS[after]||14,7)}const today=localDate();item.mastery=after;item.lastReviewed=new Date().toISOString();item.nextReview=addDays(today,days);item.reviewCount=(Number(item.reviewCount)||0)+1;if(success)item.successCount=(Number(item.successCount)||0)+1;t.history.unshift({at:new Date().toISOString(),date:today,id,surah:item.surah,ayah:item.ayah,rating,before,after,nextReview:item.nextReview,source:'memorization-test'});if(t.history.length>500)t.history.length=500;sessionStats[rating]=(sessionStats[rating]||0)+1;rated=true;save();document.querySelectorAll('[data-mtest-rate]').forEach(b=>b.disabled=true);document.getElementById('mtestNext').disabled=false;toast('تم تحديث مستوى الإتقان وموعد المراجعة ✓')}
  function next(){if(!rated)return toast('قيّم إجابتك أولًا');index++;if(index>=session.length)return finish();showQuestion()}
  function finish(){document.getElementById('mtestSession').style.display='none';document.getElementById('mtestSummary').style.display='block';document.getElementById('mtestHeroLabel').textContent='نتيجة جلسة الاختبار';document.getElementById('mtestPrompt').textContent='أحسنت، اكتملت الجلسة';document.getElementById('mtestCounter').textContent=`${session.length} آية`;document.getElementById('mtestProgress').style.width='100%';for(const [id,k] of [['mtestSAgain','again'],['mtestSHard','hard'],['mtestSGood','good'],['mtestSEasy','easy']])document.getElementById(id).textContent=sessionStats[k]||0;const strong=(sessionStats.good||0)+(sessionStats.easy||0),pct=session.length?Math.round(strong/session.length*100):0;document.getElementById('mtestSummaryText').textContent=`${strong} من ${session.length} كانت جيدة أو متقنة • ${pct}٪`;const t=tracker();t.testHistory.unshift({at:new Date().toISOString(),date:localDate(),count:session.length,scope,stats:{...sessionStats},score:pct});if(t.testHistory.length>100)t.testHistory.length=100;save()}
  function resetTest(showSetup=true){session=[];index=0;revealed=false;rated=false;sessionStats={again:0,hard:0,good:0,easy:0};const setup=document.getElementById('mtestSetup'),sess=document.getElementById('mtestSession'),sum=document.getElementById('mtestSummary');if(setup)setup.style.display=showSetup?'block':'block';if(sess)sess.style.display='none';if(sum)sum.style.display='none';const p=document.getElementById('mtestPrompt');if(p)p.textContent='اختر نوع الاختبار ثم ابدأ';const c=document.getElementById('mtestCounter');if(c)c.textContent='—';const bar=document.getElementById('mtestProgress');if(bar)bar.style.width='0%';renderSetup()}

  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject);else inject();
})();