// Memorization progress, mastery and spaced review tracker for Werd
(function(){
  const COUNTS=[7,286,200,176,120,165,206,75,129,109,123,111,43,52,99,128,111,110,98,135,112,78,118,64,77,227,93,88,69,60,34,30,73,54,45,83,182,88,75,85,54,53,89,59,37,35,38,29,18,45,60,49,62,55,78,96,29,22,24,13,14,11,11,18,12,12,30,52,52,44,28,28,20,56,40,31,50,40,46,42,29,19,36,25,22,17,19,26,30,20,15,21,11,8,8,19,5,8,8,11,11,8,3,9,5,4,7,3,6,3,5,4,5,6];
  const INTERVALS={1:1,2:3,3:7,4:14,5:30};
  const LABELS={1:'بداية',2:'قيد التثبيت',3:'جيد',4:'ثابت',5:'متقن'};
  const REMINDER_KEY='werd_mem_review_notice_v1';
  let reminderTimer=null;

  function tracker(){
    if(!state.memorizationTracker||typeof state.memorizationTracker!=='object'||Array.isArray(state.memorizationTracker))state.memorizationTracker={};
    state.memorizationTracker={version:1,items:{},history:[],settings:{reminderEnabled:true,reminderTime:'19:30',dailyGoal:5},...state.memorizationTracker};
    if(!state.memorizationTracker.items||typeof state.memorizationTracker.items!=='object'||Array.isArray(state.memorizationTracker.items))state.memorizationTracker.items={};
    if(!Array.isArray(state.memorizationTracker.history))state.memorizationTracker.history=[];
    state.memorizationTracker.settings={reminderEnabled:true,reminderTime:'19:30',dailyGoal:5,...(state.memorizationTracker.settings||{})};
    return state.memorizationTracker;
  }
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function key(s,a){return`${Number(s)}:${Number(a)}`}
  function globalStart(s){let n=1;for(let i=0;i<s-1;i++)n+=COUNTS[i]||0;return n}
  function surahName(n){const list=(Array.isArray(window.surahs)&&surahs.length)?surahs:(window.fallbackSurahs||[]);return list.find(x=>Number(x.number)===Number(n))?.name||`سورة ${n}`}
  function localDate(d=new Date()){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return`${y}-${m}-${day}`}
  function addDays(date,days){const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()+Number(days||0));return localDate(d)}
  function nowISO(){return new Date().toISOString()}
  function values(){return Object.values(tracker().items).filter(Boolean)}
  function dueItems(){const today=localDate();return values().filter(x=>!x.archived&&String(x.nextReview||today)<=today).sort((a,b)=>String(a.nextReview).localeCompare(String(b.nextReview))||a.surah-b.surah||a.ayah-b.ayah)}
  function masteryAvg(){const a=values().filter(x=>!x.archived);return a.length?a.reduce((s,x)=>s+(Number(x.mastery)||1),0)/a.length:0}
  function masteredCount(){return values().filter(x=>!x.archived&&Number(x.mastery)>=5).length}
  function reviewedToday(){const t=localDate();return tracker().history.filter(x=>x.date===t).length}
  function clampMastery(n){return Math.max(1,Math.min(5,Number(n)||1))}

  function markMemorized(surah,ayah,global,mastery=1){
    surah=Number(surah);ayah=Number(ayah);if(!surah||!ayah)return false;const t=tracker(),id=key(surah,ayah),today=localDate(),old=t.items[id];
    t.items[id]={id,surah,ayah,global:Number(global)||globalStart(surah)+ayah-1,surahName:old?.surahName||surahName(surah),mastery:clampMastery(old?.mastery||mastery),createdAt:old?.createdAt||nowISO(),lastReviewed:old?.lastReviewed||null,nextReview:old?.nextReview||addDays(today,1),reviewCount:Number(old?.reviewCount)||0,successCount:Number(old?.successCount)||0,lapses:Number(old?.lapses)||0,archived:false};
    save();renderAll();toast(old?'الآية موجودة في متابعة الحفظ':'تم تسجيل الآية ضمن الحفظ ✓');return true;
  }
  function removeItem(id){const t=tracker();delete t.items[id];save();renderAll();toast('تمت إزالة الآية من متابعة الحفظ')}

  function rate(id,rating){
    const t=tracker(),x=t.items[id];if(!x)return;const before=clampMastery(x.mastery);let after=before,days=1,success=true;
    if(rating==='again'){after=1;days=1;success=false;x.lapses=(Number(x.lapses)||0)+1}
    else if(rating==='hard'){after=Math.max(1,before);days=Math.max(1,Math.ceil((INTERVALS[after]||1)/2))}
    else if(rating==='good'){after=Math.min(5,before+1);days=INTERVALS[after]||7}
    else if(rating==='easy'){after=Math.min(5,before+2);days=Math.max(INTERVALS[after]||14,7)}
    const today=localDate();x.mastery=after;x.lastReviewed=nowISO();x.nextReview=addDays(today,days);x.reviewCount=(Number(x.reviewCount)||0)+1;if(success)x.successCount=(Number(x.successCount)||0)+1;
    t.history.unshift({at:nowISO(),date:today,id,surah:x.surah,ayah:x.ayah,rating,before,after,nextReview:x.nextReview});if(t.history.length>500)t.history.length=500;
    save();renderAll();toast(`المراجعة التالية: ${formatDate(x.nextReview)} ✓`)
  }
  function formatDate(v){if(!v)return'—';try{return new Intl.DateTimeFormat('ar-SA',{day:'numeric',month:'short'}).format(new Date(`${v}T12:00:00`))}catch(e){return v}}
  function masteryDots(n){n=clampMastery(n);return`<span class="mtrack-dots">${Array.from({length:5},(_,i)=>`<i class="${i<n?'on':''}"></i>`).join('')}</span>`}

  function injectStyles(){if(document.getElementById('werdMemTrackerStyle'))return;const s=document.createElement('style');s.id='werdMemTrackerStyle';s.textContent=`
    .mtrack-hero{background:linear-gradient(145deg,var(--green),#173f34);color:#fff;border-radius:24px;padding:18px}.mtrack-hero-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:13px}.mtrack-hero-stat{background:rgba(255,255,255,.1);border-radius:16px;padding:10px;text-align:center}.mtrack-hero-stat b{font-size:22px;display:block}.mtrack-hero-stat small{opacity:.75;font-size:9px}
    .mtrack-item{border-bottom:1px solid var(--line);padding:13px 0}.mtrack-item:last-child{border-bottom:0}.mtrack-title{display:flex;gap:8px;align-items:center;justify-content:space-between}.mtrack-title b{font-size:14px}.mtrack-meta{font-size:10px;color:var(--muted);margin-top:4px}.mtrack-dots{display:inline-flex;gap:3px;direction:ltr}.mtrack-dots i{width:7px;height:7px;border-radius:50%;background:var(--line)}.mtrack-dots i.on{background:var(--green)}.mtrack-rate{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin-top:10px}.mtrack-rate button{font-size:10px;padding:8px 4px}.mtrack-actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:9px}.mtrack-due{background:color-mix(in srgb,var(--sage) 58%,transparent);border-radius:15px;padding-inline:10px}.mtrack-empty{text-align:center;padding:28px;color:var(--muted);line-height:1.8}.mtrack-home{margin-top:12px}.mtrack-home .row{align-items:center}.mtrack-settings{display:grid;grid-template-columns:1fr 120px;gap:10px;align-items:center}.mtrack-settings input[type=time],.mtrack-settings input[type=number]{width:100%;border:1px solid var(--line);background:var(--card);color:var(--ink);border-radius:12px;padding:9px}.mtrack-filter{display:flex;gap:6px;overflow:auto;padding-bottom:4px}.mtrack-filter button.active{background:var(--green);color:#fff;border-color:var(--green)}
    @media(max-width:370px){.mtrack-hero-grid{grid-template-columns:1fr}.mtrack-rate{grid-template-columns:1fr 1fr}.mtrack-settings{grid-template-columns:1fr}}
  `;document.head.appendChild(s)}

  function inject(){injectStyles();tracker();const main=document.querySelector('main');if(!main)return;
    if(!document.getElementById('memorizationTracker')){const sec=document.createElement('section');sec.className='page';sec.id='memorizationTracker';sec.innerHTML=`
      <div class="section-title"><h3>متابعة الحفظ</h3><button class="smallbtn" id="mtrackBack">الحفظ</button></div>
      <div class="mtrack-hero"><div class="row"><div><b style="font-size:18px">مراجعتك اليوم</b><div style="opacity:.75;font-size:11px;margin-top:3px" id="mtrackHeroSub">—</div></div><span id="mtrackHeroMastery">🌱</span></div><div class="mtrack-hero-grid"><div class="mtrack-hero-stat"><b id="mtrackTotal">0</b><small>آيات في الحفظ</small></div><div class="mtrack-hero-stat"><b id="mtrackDue">0</b><small>مستحقة اليوم</small></div><div class="mtrack-hero-stat"><b id="mtrackMastered">0</b><small>متقنة</small></div></div></div>
      <div class="card" style="margin-top:10px"><div class="row"><b>تنبيه المراجعة</b><label><input type="checkbox" id="mtrackReminderOn"> مفعل</label></div><div class="mtrack-settings" style="margin-top:10px"><div><div class="muted">وقت التذكير اليومي</div><div class="muted" style="font-size:9px;margin-top:3px">يظهر عند وجود آيات مستحقة.</div></div><input type="time" id="mtrackReminderTime"></div><div class="mtrack-settings" style="margin-top:9px"><div><div class="muted">هدف المراجعة اليومي</div></div><input type="number" id="mtrackDailyGoal" min="1" max="50" inputmode="numeric"></div></div>
      <div class="section-title"><h3>الآيات</h3><span id="mtrackCountLabel">0</span></div><div class="mtrack-filter"><button class="smallbtn active" data-mtrack-filter="due">مستحق اليوم</button><button class="smallbtn" data-mtrack-filter="all">الكل</button><button class="smallbtn" data-mtrack-filter="mastered">المتقن</button></div><div class="card" id="mtrackList" style="margin-top:8px"></div>
      <div class="section-title"><h3>آخر المراجعات</h3><span id="mtrackHistoryLabel">—</span></div><div class="card" id="mtrackHistory"></div>`;main.appendChild(sec)}
    addEntries();addHomeCard();wire();decorateReader();renderAll();startReminderWatch();
  }

  let filter='due';
  function addEntries(){
    const mg=document.querySelector('#more .more-grid');if(mg&&!document.getElementById('moreMemTrackTile')){const b=document.createElement('button');b.className='more-tile';b.id='moreMemTrackTile';b.innerHTML='<span class="mi">📈</span><b>متابعة الحفظ</b><small>الإتقان والمراجعات المستحقة</small>';b.onclick=openTracker;mg.insertBefore(b,mg.firstChild)}
    const memTitle=document.querySelector('#memorization .section-title');if(memTitle&&!document.getElementById('memTrackerBtn')){const b=document.createElement('button');b.className='smallbtn';b.id='memTrackerBtn';b.textContent='📈 المتابعة';b.onclick=openTracker;memTitle.appendChild(b)}
  }
  function addHomeCard(){const home=document.getElementById('home');if(!home||document.getElementById('mtrackHomeCard'))return;const card=document.createElement('div');card.className='card mtrack-home';card.id='mtrackHomeCard';card.innerHTML='<div class="row"><div><b id="mtrackHomeTitle">مراجعة الحفظ</b><div class="muted" id="mtrackHomeSub">لا توجد مراجعات مستحقة</div></div><button class="smallbtn" id="mtrackHomeBtn">فتح</button></div>';const smart=home.querySelector('.smart-home,.home-smart,.hero');(smart?.parentNode||home).insertBefore(card,smart?.nextSibling||home.firstChild);document.getElementById('mtrackHomeBtn').onclick=openTracker}
  function decorateReader(){document.querySelectorAll('#ayahs .ayah').forEach(node=>{const tools=node.querySelector('.reader-tools');if(!tools||tools.querySelector('.mtrack-mark-btn'))return;const ay=Number(node.querySelector('.an')?.textContent||0);if(!ay)return;const s=Number(state.lastSurah?.number||state.lastSurah||state.memorization?.surah||1),id=key(s,ay),exists=!!tracker().items[id];const b=document.createElement('button');b.className='smallbtn mtrack-mark-btn';b.textContent=exists?'✓ في الحفظ':'✓ حفظت';b.onclick=()=>{markMemorized(s,ay,globalStart(s)+ay-1);decorateReader()};tools.appendChild(b)})}
  function openTracker(){filter='due';go('memorizationTracker');renderAll()} window.openWerdMemorizationTracker=openTracker;

  function wire(){const $=id=>document.getElementById(id);$('mtrackBack').onclick=()=>{if(typeof openWerdMemorization==='function')openWerdMemorization();else go('quran')};document.querySelectorAll('[data-mtrack-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.mtrackFilter;document.querySelectorAll('[data-mtrack-filter]').forEach(x=>x.classList.toggle('active',x.dataset.mtrackFilter===filter));renderList()});$('mtrackReminderOn').onchange=saveSettings;$('mtrackReminderTime').onchange=saveSettings;$('mtrackDailyGoal').onchange=saveSettings;const ay=document.getElementById('ayahs');if(ay)new MutationObserver(()=>decorateReader()).observe(ay,{childList:true,subtree:true})}
  function saveSettings(){const s=tracker().settings;s.reminderEnabled=document.getElementById('mtrackReminderOn').checked;s.reminderTime=document.getElementById('mtrackReminderTime').value||'19:30';s.dailyGoal=Math.max(1,Math.min(50,Number(document.getElementById('mtrackDailyGoal').value)||5));save();renderAll();toast('تم حفظ إعدادات مراجعة الحفظ ✓')}

  function renderAll(){if(!document.getElementById('memorizationTracker'))return;const t=tracker(),all=values().filter(x=>!x.archived),due=dueItems();document.getElementById('mtrackTotal').textContent=all.length;document.getElementById('mtrackDue').textContent=due.length;document.getElementById('mtrackMastered').textContent=masteredCount();document.getElementById('mtrackHeroSub').textContent=due.length?`${due.length} آية تنتظر المراجعة • أنجزت ${reviewedToday()} اليوم`:`أحسنت، لا توجد مراجعات مستحقة اليوم`;document.getElementById('mtrackHeroMastery').textContent=masteryAvg()>=4.5?'🏆':masteryAvg()>=3?'🌿':'🌱';document.getElementById('mtrackReminderOn').checked=!!t.settings.reminderEnabled;document.getElementById('mtrackReminderTime').value=t.settings.reminderTime||'19:30';document.getElementById('mtrackDailyGoal').value=String(t.settings.dailyGoal||5);renderList();renderHistory();renderHome();decorateReader()}
  function renderList(){const box=document.getElementById('mtrackList');if(!box)return;const today=localDate();let arr=values().filter(x=>!x.archived);if(filter==='due')arr=dueItems();else if(filter==='mastered')arr=arr.filter(x=>Number(x.mastery)>=5);else arr.sort((a,b)=>a.surah-b.surah||a.ayah-b.ayah);document.getElementById('mtrackCountLabel').textContent=`${arr.length} آية`;if(!arr.length){box.innerHTML=`<div class="mtrack-empty">${filter==='due'?'لا توجد مراجعات مستحقة الآن 🌿':'لا توجد آيات في هذا القسم.'}</div>`;return}box.innerHTML=arr.map(x=>`<div class="mtrack-item ${String(x.nextReview)<=today?'mtrack-due':''}" data-track-id="${esc(x.id)}"><div class="mtrack-title"><b>${esc(x.surahName)} • الآية ${x.ayah}</b>${masteryDots(x.mastery)}</div><div class="mtrack-meta">${LABELS[clampMastery(x.mastery)]} • المراجعة ${String(x.nextReview)<=today?'مستحقة الآن':formatDate(x.nextReview)} • ${x.reviewCount||0} مراجعات</div><div class="mtrack-actions"><button class="smallbtn" data-review="${esc(x.id)}">🧠 مراجعة الآية</button><button class="smallbtn" data-open="${esc(x.id)}">📖 فتح</button><button class="smallbtn" data-remove="${esc(x.id)}">إزالة</button></div><div class="mtrack-rate"><button class="smallbtn" data-rate="again" data-id="${esc(x.id)}">أعدها</button><button class="smallbtn" data-rate="hard" data-id="${esc(x.id)}">صعب</button><button class="smallbtn" data-rate="good" data-id="${esc(x.id)}">جيد</button><button class="smallbtn" data-rate="easy" data-id="${esc(x.id)}">متقن</button></div></div>`).join('');box.querySelectorAll('[data-rate]').forEach(b=>b.onclick=()=>rate(b.dataset.id,b.dataset.rate));box.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>{const x=tracker().items[b.dataset.review];if(x&&typeof openWerdMemorization==='function')openWerdMemorization(x.surah,x.ayah)});box.querySelectorAll('[data-open]').forEach(b=>b.onclick=async()=>{const x=tracker().items[b.dataset.open];if(!x)return;go('quran');await openSurah(x.surah);setTimeout(()=>document.getElementById(`ayah-${x.ayah}`)?.scrollIntoView({behavior:'smooth',block:'center'}),150)});box.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{if(confirm('إزالة هذه الآية من متابعة الحفظ؟'))removeItem(b.dataset.remove)})}
  function renderHistory(){const box=document.getElementById('mtrackHistory');if(!box)return;const h=tracker().history.slice(0,8);document.getElementById('mtrackHistoryLabel').textContent=h.length?`${h.length} أخيرة`:'—';if(!h.length){box.innerHTML='<div class="mtrack-empty">بعد أول تقييم للمراجعة سيظهر السجل هنا.</div>';return}const rateLabel={again:'أعدها',hard:'صعب',good:'جيد',easy:'متقن'};box.innerHTML=h.map(x=>`<div class="list-item"><span>${esc(surahName(x.surah))} • ${x.ayah}<small style="display:block;color:var(--muted)">${rateLabel[x.rating]||x.rating}</small></span><span class="badge">${x.before} ← ${x.after}</span></div>`).join('')}
  function renderHome(){const card=document.getElementById('mtrackHomeCard');if(!card)return;const d=dueItems(),goal=Number(tracker().settings.dailyGoal)||5,done=reviewedToday();document.getElementById('mtrackHomeTitle').textContent=d.length?`لديك ${d.length} آية للمراجعة`:'مراجعة الحفظ مكتملة';document.getElementById('mtrackHomeSub').textContent=d.length?`هدفك اليوم ${goal} • راجعت ${done}`:`راجعت ${done} اليوم • لا توجد آيات مستحقة`;card.style.borderColor=d.length?'var(--green)':''}

  async function maybeNotify(){const t=tracker(),d=dueItems();if(!t.settings.reminderEnabled||!d.length)return;const time=t.settings.reminderTime||'19:30',m=time.match(/^(\d{1,2}):(\d{2})$/);if(!m)return;const now=new Date(),nowMin=now.getHours()*60+now.getMinutes(),target=Number(m[1])*60+Number(m[2]);if(nowMin<target)return;const today=localDate();if(localStorage.getItem(REMINDER_KEY)===today)return;localStorage.setItem(REMINDER_KEY,today);toast(`لديك ${d.length} آية مستحقة للمراجعة اليوم`);if('Notification'in window&&Notification.permission==='granted'&&'serviceWorker'in navigator){try{const reg=await navigator.serviceWorker.ready;await reg.showNotification('مراجعة الحفظ 🧠',{body:`لديك ${d.length} آية مستحقة للمراجعة اليوم في ورد.`,icon:'./icon.svg',badge:'./icon.svg',dir:'rtl',lang:'ar',tag:'werd-memorization-review',data:{url:'./'}})}catch(e){console.warn(e)}}}
  function startReminderWatch(){if(reminderTimer)clearInterval(reminderTimer);maybeNotify();reminderTimer=setInterval(maybeNotify,60000);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')maybeNotify()})}

  const baseRender=typeof renderState==='function'?renderState:null;if(baseRender)renderState=function(){baseRender();tracker();renderAll()};
  inject();
})();