// Werd Mushaf V2 — independent reader with same-origin + direct trusted fallback.
(function(){
 const TOTAL=604; let page=1,seq=0,ctl=null,ayahs=[],touchX=null,touchY=null;
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const clamp=n=>Math.max(1,Math.min(TOTAL,Number(n)||1));
 function saved(){if(!window.state)window.state={};if(!state.mushafV2||typeof state.mushafV2!=='object')state.mushafV2={page:1};state.mushafV2.page=clamp(state.mushafV2.page);return state.mushafV2}
 function persist(){try{if(typeof save==='function')save()}catch(e){}}
 function styles(){if(document.getElementById('mushafV2Style'))return;const s=document.createElement('style');s.id='mushafV2Style';s.textContent=`#mushafV2{padding-bottom:110px}.mv2{max-width:780px;margin:auto}.mv2-head{position:sticky;top:0;z-index:40;background:var(--bg);padding:8px 0 12px}.mv2-row{display:flex;align-items:center;justify-content:space-between;gap:8px}.mv2-title{text-align:center}.mv2-title b{font-size:20px}.mv2-status{font-size:11px;color:var(--muted);margin-top:3px}.mv2-badges{display:flex;justify-content:center;gap:7px;margin-top:9px}.mv2-badge{padding:6px 10px;border:1px solid var(--line);border-radius:999px;background:var(--card);font-size:11px}.mv2-sheet{background:#fffdf5;color:#173e30;border:1px solid #ddd3bc;border-radius:22px;min-height:66vh;padding:24px 20px;box-shadow:0 16px 42px rgba(20,55,40,.09)}.dark .mv2-sheet{background:#13261e;color:#f7f0df}.mv2-loading,.mv2-error{text-align:center;padding:90px 20px;color:var(--muted)}.mv2-spinner{width:30px;height:30px;border:3px solid #d8e2dc;border-top-color:var(--green);border-radius:50%;margin:0 auto 14px;animation:spin .8s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}.mv2-surah{text-align:center;margin:13px auto 9px;padding:9px 14px;max-width:340px;border-radius:999px;background:var(--sage);font-size:19px;font-weight:900}.mv2-text{direction:rtl;text-align:justify;text-align-last:center;font-family:"Traditional Arabic","Noto Naskh Arabic",serif;font-size:27px;line-height:2.35}.mv2-ayah{border-radius:7px}.mv2-ayah.sel{background:#efe3bd}.mv2-num{display:inline-grid;place-items:center;min-width:28px;height:28px;border:1px solid currentColor;border-radius:50%;font:800 11px system-ui;margin:0 4px}.mv2-footer,.mv2-source{text-align:center;color:var(--muted);font-size:10px;margin-top:14px}.mv2-nav{display:grid;grid-template-columns:1fr auto 1fr;gap:8px;align-items:center;margin-top:12px}.mv2-nav button,.mv2-retry{border:1px solid var(--line);background:var(--card);color:var(--ink);border-radius:15px;padding:12px;font-weight:900}.mv2-pagebox{display:flex;align-items:center;gap:5px}.mv2-pagebox input{width:65px;text-align:center;border:1px solid var(--line);border-radius:13px;padding:10px}.mv2-range{width:100%;accent-color:var(--green);margin-top:12px}@media(max-width:430px){.mv2-sheet{padding:18px 13px}.mv2-text{font-size:24px;line-height:2.25}}`;document.head.appendChild(s)}
 function mount(){styles();const main=document.querySelector('main');if(!main)return;let sec=document.getElementById('mushafV2');if(!sec){sec=document.createElement('section');sec.className='page';sec.id='mushafV2';sec.innerHTML=`<div class="mv2"><div class="mv2-head"><div class="mv2-row"><button class="smallbtn" id="mv2Back">فهرس السور</button><div class="mv2-title"><b>المصحف الكريم</b><div class="mv2-status" id="mv2Status">جاهز</div></div><button class="smallbtn" id="mv2Resume">آخر موضع</button></div><div class="mv2-badges"><span class="mv2-badge" id="mv2Surah">—</span><span class="mv2-badge" id="mv2Juz">الجزء —</span></div></div><div class="mv2-sheet" id="mv2Sheet"></div><div class="mv2-nav"><button id="mv2Prev">→ السابقة</button><div class="mv2-pagebox"><input id="mv2Input" type="number" min="1" max="604"><span>/604</span></div><button id="mv2Next">التالية ←</button></div><input class="mv2-range" id="mv2Range" type="range" min="1" max="604"><div class="mv2-source" id="mv2Source"></div></div>`;main.appendChild(sec);wire(sec)}return sec}
 function wire(sec){sec.querySelector('#mv2Back').onclick=()=>go('quran');sec.querySelector('#mv2Resume').onclick=()=>load(saved().page,saved().globalAyah);sec.querySelector('#mv2Prev').onclick=()=>load(page-1);sec.querySelector('#mv2Next').onclick=()=>load(page+1);sec.querySelector('#mv2Input').onchange=e=>load(e.target.value);sec.querySelector('#mv2Range').onchange=e=>load(e.target.value);const sh=sec.querySelector('#mv2Sheet');sh.addEventListener('touchstart',e=>{const t=e.changedTouches?.[0];if(t){touchX=t.clientX;touchY=t.clientY}},{passive:true});sh.addEventListener('touchend',e=>{const t=e.changedTouches?.[0];if(!t||touchX==null)return;const dx=t.clientX-touchX,dy=t.clientY-touchY;touchX=touchY=null;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.25)load(dx<0?page+1:page-1)},{passive:true})}
 function ui(p){document.getElementById('mv2Input').value=p;document.getElementById('mv2Range').value=p;document.getElementById('mv2Prev').disabled=p<=1;document.getElementById('mv2Next').disabled=p>=TOTAL}
 function loading(p){document.getElementById('mv2Sheet').innerHTML='<div class="mv2-loading"><div class="mv2-spinner"></div><b>تحميل صفحة المصحف…</b></div>';document.getElementById('mv2Status').textContent=`صفحة ${p}`}
 function error(p){document.getElementById('mv2Sheet').innerHTML='<div class="mv2-error"><b>تعذر تحميل الصفحة</b><div style="margin:8px 0 16px">تحقق من الاتصال ثم أعد المحاولة.</div><button class="mv2-retry" id="mv2Retry">إعادة المحاولة</button></div>';document.getElementById('mv2Retry').onclick=()=>load(p)}
 function normalizeCloud(j,p){return(j.data?.ayahs||[]).map(a=>({number:a.number,numberInSurah:a.numberInSurah,text:a.text,juz:a.juz,page:a.page||p,surah:{number:a.surah?.number,name:a.surah?.name}}))}
 async function request(url,signal,ms){const timer=setTimeout(()=>ctl?.abort(),ms);try{const r=await fetch(url,{signal,cache:'no-store',headers:{Accept:'application/json'}});if(!r.ok)throw Error(String(r.status));return await r.json()}finally{clearTimeout(timer)}}
 async function fetchPage(p){if(ctl)ctl.abort();ctl=new AbortController();const signal=ctl.signal;
  try{const j=await request(`/api/mushaf/${p}?v=3`,signal,5500);if(j.ok&&Array.isArray(j.ayahs)&&j.ayahs.length)return{ayahs:j.ayahs,source:'خادم ورد'}}catch(e){if(e?.name==='AbortError')ctl=new AbortController()}
  try{const j=await request(`https://api.alquran.cloud/v1/page/${p}/quran-uthmani`,ctl.signal,7000),list=normalizeCloud(j,p);if(list.length)return{ayahs:list,source:'AlQuran Cloud'}}catch(e){}
  throw Error('unavailable')}
 function render(data,anchor){ayahs=data.ayahs;if(!ayahs.length)return error(page);let html='<div class="mv2-text">',last=0;for(const a of ayahs){const sn=Number(a.surah?.number)||0;if(sn!==last){html+=`<div class="mv2-surah">${esc(a.surah?.name||'')}</div>`;last=sn}html+=`<span class="mv2-ayah" data-g="${Number(a.number)}">${esc(a.text)} <span class="mv2-num">${Number(a.numberInSurah)}</span> </span>`}html+=`</div><div class="mv2-footer">صفحة ${page} من ${TOTAL}</div>`;const sh=document.getElementById('mv2Sheet');sh.innerHTML=html;sh.querySelectorAll('.mv2-ayah').forEach(n=>n.onclick=()=>select(Number(n.dataset.g),true));const first=ayahs[0],lastA=ayahs[ayahs.length-1];document.getElementById('mv2Surah').textContent=first.surah?.number===lastA.surah?.number?(first.surah?.name||'سورة'):`${first.surah?.name||''} • ${lastA.surah?.name||''}`;document.getElementById('mv2Juz').textContent=`الجزء ${first.juz||'—'}`;document.getElementById('mv2Status').textContent=`صفحة ${page}`;document.getElementById('mv2Source').textContent=`مصدر النص: ${data.source}`;select(anchor||first.number,false)}
 function select(g,notify){const a=ayahs.find(x=>Number(x.number)===Number(g));if(!a)return;document.querySelectorAll('#mv2Sheet .mv2-ayah').forEach(n=>n.classList.toggle('sel',Number(n.dataset.g)===Number(g)));const s=saved();s.page=page;s.globalAyah=Number(a.number);s.surahNumber=Number(a.surah?.number);s.ayahNumber=Number(a.numberInSurah);s.surahName=a.surah?.name||'';persist();if(notify&&typeof toast==='function')toast(`تم حفظ موضعك: ${s.surahName} • الآية ${s.ayahNumber}`)}
 async function load(p,anchor=null){p=clamp(p);const my=++seq;page=p;ui(p);loading(p);try{const data=await fetchPage(p);if(my!==seq)return;render(data,anchor);window.scrollTo({top:0,behavior:'smooth'})}catch(e){if(my===seq)error(p)}}
 window.openMushaf=window.openWerdMushafV2=function(p=null){mount();go('mushafV2');const s=saved();load(p||s.page,p?null:s.globalAyah)};window.openMushafForSurah=()=>window.openMushaf();
 document.addEventListener('DOMContentLoaded',()=>mount());
})();