// Werd Mushaf V2 — rebuilt from scratch. Independent from legacy mushaf.js/resilience.
(function(){
  const TOTAL=604;
  let page=1, requestSeq=0, controller=null, ayahs=[], selected=null, touchX=null, touchY=null;

  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const clamp=n=>Math.max(1,Math.min(TOTAL,Number(n)||1));
  function saved(){
    if(!window.state)window.state={};
    if(!state.mushafV2||typeof state.mushafV2!=='object')state.mushafV2={page:1,globalAyah:null,surahNumber:null,ayahNumber:null,surahName:'',updatedAt:null};
    state.mushafV2.page=clamp(state.mushafV2.page);
    return state.mushafV2;
  }
  function persist(){try{if(typeof save==='function')save()}catch(e){}}

  function styles(){if(document.getElementById('mushafV2Style'))return;const s=document.createElement('style');s.id='mushafV2Style';s.textContent=`
    #mushafV2{padding-bottom:110px}.mv2{max-width:780px;margin:0 auto}.mv2-head{position:sticky;top:0;z-index:40;background:color-mix(in srgb,var(--bg) 94%,transparent);backdrop-filter:blur(16px);padding:8px 0 12px}.mv2-row{display:flex;align-items:center;justify-content:space-between;gap:8px}.mv2-title{text-align:center}.mv2-title b{font-size:18px}.mv2-status{font-size:11px;color:var(--muted);margin-top:3px}.mv2-badges{display:flex;justify-content:center;gap:7px;flex-wrap:wrap;margin-top:9px}.mv2-badge{padding:6px 10px;border:1px solid var(--line);border-radius:999px;background:var(--card);font-size:11px}.mv2-version{font-size:10px;color:var(--muted);text-align:center;margin-top:6px}.mv2-sheet{background:#fffdf5;color:#173e30;border:1px solid #ddd3bc;border-radius:22px;min-height:66vh;padding:24px 20px;box-shadow:0 16px 42px rgba(20,55,40,.09)}.dark .mv2-sheet{background:#13261e;color:#f7f0df;border-color:#315043}.mv2-loading,.mv2-error{text-align:center;padding:90px 20px;color:var(--muted)}.mv2-spinner{width:30px;height:30px;border:3px solid color-mix(in srgb,var(--green) 20%,transparent);border-top-color:var(--green);border-radius:50%;margin:0 auto 14px;animation:mv2spin .8s linear infinite}@keyframes mv2spin{to{transform:rotate(360deg)}}.mv2-orn{text-align:center;color:var(--green);opacity:.55;letter-spacing:7px;margin-bottom:12px}.mv2-surah{text-align:center;margin:13px auto 9px;padding:9px 14px;width:min(340px,92%);border-radius:999px;background:color-mix(in srgb,var(--sage) 68%,transparent);font-size:19px;font-weight:900}.mv2-text{direction:rtl;text-align:justify;text-align-last:center;font-family:"Amiri Quran","Traditional Arabic","Noto Naskh Arabic",serif;font-size:27px;line-height:2.35}.mv2-ayah{cursor:pointer;border-radius:7px}.mv2-ayah.sel{background:color-mix(in srgb,var(--gold) 24%,transparent)}.mv2-num{display:inline-grid;place-items:center;min-width:28px;height:28px;border:1px solid currentColor;border-radius:50%;font:800 11px system-ui;margin:0 4px;opacity:.8}.mv2-footer{text-align:center;color:var(--muted);font-size:11px;margin-top:16px}.mv2-nav{display:grid;grid-template-columns:1fr auto 1fr;gap:8px;align-items:center;margin-top:12px}.mv2-nav button,.mv2-retry{border:1px solid var(--line);background:var(--card);color:var(--ink);border-radius:15px;padding:12px;font-weight:900}.mv2-pagebox{display:flex;align-items:center;gap:6px}.mv2-pagebox input{width:70px;text-align:center;border:1px solid var(--line);background:var(--card);color:var(--ink);border-radius:13px;padding:10px;font-weight:900}.mv2-range{width:100%;accent-color:var(--green);margin-top:12px}.mv2-source{text-align:center;color:var(--muted);font-size:10px;margin-top:8px}@media(max-width:430px){.mv2-sheet{padding:20px 14px}.mv2-text{font-size:24px;line-height:2.25}.mv2-nav button{padding:11px 7px;font-size:12px}}
  `;document.head.appendChild(s)}

  function mount(){styles();const main=document.querySelector('main');if(!main)return null;let sec=document.getElementById('mushafV2');if(!sec){sec=document.createElement('section');sec.className='page';sec.id='mushafV2';sec.innerHTML=`<div class="mv2"><div class="mv2-head"><div class="mv2-row"><button class="smallbtn" id="mv2Back">فهرس السور</button><div class="mv2-title"><b>المصحف الكريم</b><div class="mv2-status" id="mv2Status">جاهز</div></div><button class="smallbtn" id="mv2Resume">آخر موضع</button></div><div class="mv2-badges"><span class="mv2-badge" id="mv2Surah">—</span><span class="mv2-badge" id="mv2Juz">الجزء —</span></div><div class="mv2-version">Mushaf V2</div></div><div class="mv2-sheet" id="mv2Sheet"></div><div class="mv2-nav"><button id="mv2Prev">→ السابقة</button><div class="mv2-pagebox"><input id="mv2Input" type="number" min="1" max="604" inputmode="numeric"><span class="muted">/ 604</span></div><button id="mv2Next">التالية ←</button></div><input class="mv2-range" id="mv2Range" type="range" min="1" max="604"><div class="mv2-source" id="mv2Source">مصدر النص: تحميل آمن عبر ورد</div></div>`;main.appendChild(sec);wire(sec)}return sec}
  function wire(sec){
    sec.querySelector('#mv2Back').onclick=()=>go('quran');
    sec.querySelector('#mv2Resume').onclick=()=>load(saved().page,saved().globalAyah);
    sec.querySelector('#mv2Prev').onclick=()=>load(page-1);
    sec.querySelector('#mv2Next').onclick=()=>load(page+1);
    sec.querySelector('#mv2Input').onchange=e=>load(e.target.value);
    sec.querySelector('#mv2Input').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();load(e.target.value)}};
    sec.querySelector('#mv2Range').onchange=e=>load(e.target.value);
    const sh=sec.querySelector('#mv2Sheet');sh.addEventListener('touchstart',e=>{const t=e.changedTouches?.[0];if(t){touchX=t.clientX;touchY=t.clientY}},{passive:true});sh.addEventListener('touchend',e=>{const t=e.changedTouches?.[0];if(!t||touchX==null)return;const dx=t.clientX-touchX,dy=t.clientY-touchY;touchX=touchY=null;if(Math.abs(dx)<55||Math.abs(dx)<Math.abs(dy)*1.25)return;load(dx<0?page+1:page-1)},{passive:true});
  }
  function ui(p){document.getElementById('mv2Input').value=p;document.getElementById('mv2Range').value=p;document.getElementById('mv2Prev').disabled=p<=1;document.getElementById('mv2Next').disabled=p>=TOTAL}
  function loading(p){const sh=document.getElementById('mv2Sheet');if(sh)sh.innerHTML='<div class="mv2-loading"><div class="mv2-spinner"></div><b>تحميل صفحة المصحف</b><div style="margin-top:7px">يتم الآن جلب الصفحة من خادم ورد…</div></div>';const st=document.getElementById('mv2Status');if(st)st.textContent=`تحميل صفحة ${p}…`}
  function error(p,msg){const sh=document.getElementById('mv2Sheet');if(sh)sh.innerHTML=`<div class="mv2-error"><b>تعذر تحميل صفحة المصحف</b><div style="margin:8px 0 16px">${esc(msg||'تعذر الاتصال بخادم المصحف.')}</div><button class="mv2-retry" id="mv2Retry">إعادة المحاولة</button></div>`;document.getElementById('mv2Retry')?.addEventListener('click',()=>load(p));document.getElementById('mv2Status').textContent=`تعذر تحميل صفحة ${p}`}
  function group(list){const out=[];for(const a of list){let g=out[out.length-1];if(!g||Number(g.surah?.number)!==Number(a.surah?.number)){g={surah:a.surah,ayahs:[]};out.push(g)}g.ayahs.push(a)}return out}
  function render(data,anchor){ayahs=Array.isArray(data.ayahs)?data.ayahs:[];if(!ayahs.length){error(page,'لم تصل آيات الصفحة.');return}const sh=document.getElementById('mv2Sheet'),groups=group(ayahs);sh.innerHTML=`<div class="mv2-orn">◆ ◇ ◆</div><div class="mv2-text">${groups.map(g=>`<div class="mv2-surah">${esc(g.surah?.name||'')}</div>${g.ayahs.map(a=>`<span class="mv2-ayah" data-g="${Number(a.number)}">${esc(a.text)} <span class="mv2-num">${Number(a.numberInSurah)}</span> </span>`).join('')}`).join('')}</div><div class="mv2-footer">صفحة ${page} من ${TOTAL}</div>`;sh.querySelectorAll('.mv2-ayah').forEach(n=>n.onclick=()=>select(Number(n.dataset.g),true));const first=ayahs[0];document.getElementById('mv2Surah').textContent=groups.length===1?(groups[0].surah?.name||'سورة'):`${groups[0].surah?.name||''} • ${groups[groups.length-1].surah?.name||''}`;document.getElementById('mv2Juz').textContent=`الجزء ${first.juz||'—'}`;document.getElementById('mv2Status').textContent=`صفحة ${page}`;document.getElementById('mv2Source').textContent=`مصدر النص: ${data.source==='quran.com'?'Quran.com':'AlQuran Cloud'} عبر خادم ورد`;const target=anchor&&ayahs.some(a=>Number(a.number)===Number(anchor))?Number(anchor):Number(first.number);select(target,false);if(anchor)setTimeout(()=>sh.querySelector(`[data-g="${target}"]`)?.scrollIntoView({block:'center'}),80)}
  function select(global,notify){const a=ayahs.find(x=>Number(x.number)===Number(global));if(!a)return;selected=a;document.querySelectorAll('#mv2Sheet .mv2-ayah').forEach(n=>n.classList.toggle('sel',Number(n.dataset.g)===global));const s=saved();s.page=page;s.globalAyah=Number(a.number)||null;s.surahNumber=Number(a.surah?.number)||null;s.ayahNumber=Number(a.numberInSurah)||null;s.surahName=a.surah?.name||'';s.updatedAt=new Date().toISOString();persist();if(notify&&typeof toast==='function')toast(`تم حفظ موضعك: ${s.surahName} • الآية ${s.ayahNumber}`)}
  async function fetchPage(p){if(controller)controller.abort();controller=new AbortController();const local=controller;const timeout=setTimeout(()=>local.abort(),10000);try{const r=await fetch(`/api/mushaf/${p}?v=2`,{signal:local.signal,cache:'no-store',headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`الخادم أعاد ${r.status}`);const j=await r.json();if(!j.ok||!Array.isArray(j.ayahs))throw new Error('استجابة المصحف غير صالحة');return j}finally{clearTimeout(timeout)}}
  async function load(p,anchor=null){p=clamp(p);const seq=++requestSeq;page=p;ui(p);loading(p);try{const data=await fetchPage(p);if(seq!==requestSeq)return;render(data,anchor);window.scrollTo({top:0,behavior:'smooth'})}catch(e){if(seq!==requestSeq)return;if(e?.name==='AbortError')error(p,'انتهت مهلة الاتصال. اضغط إعادة المحاولة.');else error(p,'تعذر الوصول إلى خادم المصحف. اضغط إعادة المحاولة.') }}

  window.openMushaf=function(p=null){mount();go('mushafV2');const s=saved();load(p||s.page,p?null:s.globalAyah);document.querySelectorAll('.bottom .nav').forEach(n=>n.classList.remove('active'));document.querySelector('.bottom .nav[data-page="quran"]')?.classList.add('active')};
  window.openMushafForSurah=function(){window.openMushaf()};
  document.addEventListener('DOMContentLoaded',()=>{mount();const head=document.querySelector('#quran .reader-head');if(head&&!document.getElementById('openMushafBtn')){const b=document.createElement('button');b.className='secondary';b.id='openMushafBtn';b.style.margin='0 0 12px';b.textContent='📖 فتح المصحف بالصفحات';b.onclick=()=>window.openMushaf();head.appendChild(b)}});
})();