// Offline Quran audio downloads for Werd
(function(){
  const CACHE='werd-audio-offline-v1';
  const KEY='werd_audio_offline_manifest_v1';
  const CDN='https://cdn.islamic.network/quran/audio';
  const BITRATE=128;
  const RECITERS=[['ar.alafasy','مشاري العفاسي'],['ar.sudais','عبدالرحمن السديس'],['ar.mahermuaiqly','ماهر المعيقلي'],['ar.husary','محمود خليل الحصري'],['ar.hudhaify','علي الحذيفي'],['ar.shuraim','سعود الشريم'],['ar.ajamy','أحمد العجمي'],['ar.abdullahbasfar','عبدالله بصفر']];
  const COUNTS=[7,286,200,176,120,165,206,75,129,109,123,111,43,52,99,128,111,110,98,135,112,78,118,64,77,227,93,88,69,60,34,30,73,54,45,83,182,88,75,85,54,53,89,59,37,35,38,29,18,45,60,49,62,55,78,96,29,22,24,13,14,11,11,18,12,12,30,52,52,44,28,28,20,56,40,31,50,40,46,42,29,19,36,25,22,17,19,26,30,20,15,21,11,8,8,19,5,8,8,11,11,8,3,9,5,4,7,3,6,3,5,4,5,6];
  let chosen=new Set(),busy=false,cancel=false;
  function read(){try{return JSON.parse(localStorage.getItem(KEY)||'null')||{items:{},sizes:{}}}catch(e){return{items:{},sizes:{}}}}
  function save(m){m.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(m))}
  function start(s){let n=1;for(let i=0;i<s-1;i++)n+=COUNTS[i];return n}
  function urls(s,r){const a=start(s),n=COUNTS[s-1];return Array.from({length:n},(_,i)=>`${CDN}/${BITRATE}/${r}/${a+i}.mp3`)}
  function name(s){const list=(Array.isArray(window.surahs)&&surahs.length)?surahs:(window.fallbackSurahs||[]);return list.find(x=>Number(x.number)===s)?.name||`سورة ${s}`}
  function bytes(n){n=Number(n)||0;return n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`}
  function inject(){
    if(!document.getElementById('offlineAudioStyle')){const st=document.createElement('style');st.id='offlineAudioStyle';st.textContent=`.oa-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;max-height:360px;overflow:auto}.oa-s{border:1px solid var(--line);background:var(--card);color:var(--ink);border-radius:14px;padding:9px 5px;font-size:11px;font-weight:800}.oa-s.on{outline:2px solid var(--green);background:var(--sage)}.oa-s.saved:after{content:' ✓';color:var(--green)}.oa-bar{height:10px;background:var(--sage);border-radius:99px;overflow:hidden}.oa-bar span{display:block;height:100%;width:0;background:var(--green)}@media(min-width:470px){.oa-grid{grid-template-columns:repeat(5,1fr)}}`;document.head.appendChild(st)}
    const main=document.querySelector('main');if(!main)return;if(!document.getElementById('offlineAudio')){const sec=document.createElement('section');sec.className='page';sec.id='offlineAudio';sec.innerHTML=`<div class="section-title"><h3>التلاوات دون إنترنت</h3><button class="smallbtn" id="oaBack">الاستماع</button></div><div class="card"><b>القارئ</b><select class="listen-select" id="oaReciter" style="margin-top:9px;width:100%">${RECITERS.map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('')}</select><div class="muted" style="margin-top:7px">تنزيل بجودة 128 kbps. الملفات تبقى على هذا الجهاز فقط.</div></div><div class="card" style="margin-top:10px"><div class="row"><b>اختر السور</b><span><button class="smallbtn" id="oaAll">الكل</button> <button class="smallbtn" id="oaNone">مسح</button></span></div><div class="oa-grid" id="oaGrid" style="margin-top:10px"></div></div><div class="card" style="margin-top:10px"><div class="row"><b id="oaSummary">لا توجد تلاوات محفوظة</b><button class="smallbtn" id="oaDeleteAll">حذف الكل</button></div><div class="row" style="margin-top:10px"><button class="primary" id="oaDownload" style="margin:0">⇩ تنزيل المحدد</button><button class="secondary" id="oaDelete" style="margin:0">حذف المحدد</button></div><div class="oa-bar" style="margin-top:12px"><span id="oaBar"></span></div><div class="row muted" style="margin-top:7px"><span id="oaStatus">جاهز</span><span id="oaSize">0 MB</span></div><button class="smallbtn" id="oaCancel" style="display:none;margin-top:8px">إيقاف التنزيل</button></div>`;main.appendChild(sec)}
    const lc=document.querySelector('#listening .section-title');if(lc&&!document.getElementById('oaEntry')){const b=document.createElement('button');b.className='smallbtn';b.id='oaEntry';b.textContent='⇩ تنزيل التلاوات';b.onclick=open;lc.appendChild(b)}
    const mg=document.querySelector('#more .more-grid');if(mg&&!document.getElementById('moreOfflineAudio')){const b=document.createElement('button');b.className='more-tile';b.id='moreOfflineAudio';b.innerHTML='<span class="mi">🎧</span><b>تلاوات دون إنترنت</b><small>تنزيل السور بصوت القارئ</small>';b.onclick=open;mg.insertBefore(b,mg.firstChild)}
    wire();render();
  }
  function wire(){const $=id=>document.getElementById(id);$('oaBack').onclick=()=>go('listening');$('oaAll').onclick=()=>{chosen=new Set(Array.from({length:114},(_,i)=>i+1));renderGrid()};$('oaNone').onclick=()=>{chosen.clear();renderGrid()};$('oaDownload').onclick=download;$('oaDelete').onclick=del;$('oaDeleteAll').onclick=delAll;$('oaCancel').onclick=()=>cancel=true;$('oaReciter').onchange=render}
  function open(){go('offlineAudio');render()} window.openOfflineAudioManager=open;
  function render(){if(!document.getElementById('offlineAudio'))return;const sel=document.getElementById('oaReciter');if(!sel.value)sel.value=state.listening?.reciter||'ar.alafasy';renderGrid();summary()}
  function renderGrid(){const box=document.getElementById('oaGrid');if(!box)return;const r=document.getElementById('oaReciter').value,m=read();box.innerHTML=Array.from({length:114},(_,i)=>i+1).map(s=>`<button class="oa-s ${chosen.has(s)?'on':''} ${m.items[`${r}:${s}`]?'saved':''}" data-s="${s}">${s}. ${name(s)}</button>`).join('');box.querySelectorAll('[data-s]').forEach(b=>b.onclick=()=>{const s=Number(b.dataset.s);chosen.has(s)?chosen.delete(s):chosen.add(s);renderGrid()})}
  function summary(){const m=read(),keys=Object.keys(m.items),total=Object.values(m.sizes).reduce((a,b)=>a+(Number(b)||0),0);document.getElementById('oaSummary').textContent=keys.length?`${keys.length} سورة/قارئ محفوظة`:'لا توجد تلاوات محفوظة';document.getElementById('oaSize').textContent=bytes(total)}
  function setBusy(v){busy=v;document.getElementById('oaDownload').disabled=v;document.getElementById('oaDelete').disabled=v;document.getElementById('oaCancel').style.display=v?'inline-block':'none'}
  async function download(){if(busy)return;if(!chosen.size)return toast('اختر سورة واحدة على الأقل');if(!navigator.onLine)return toast('يلزم اتصال بالإنترنت للتنزيل');busy=true;cancel=false;setBusy(true);const r=document.getElementById('oaReciter').value,m=read(),cache=await caches.open(CACHE);const tasks=[];[...chosen].sort((a,b)=>a-b).forEach(s=>urls(s,r).forEach((u,i)=>tasks.push({s,u,last:i===COUNTS[s-1]-1})));let done=0,size=0;try{for(const t of tasks){if(cancel)break;const req=new Request(t.u);const res=await fetch(req,{cache:'no-store'});if(!res.ok)throw new Error('audio');const c=res.clone(),z=res.clone();await cache.put(req,c);let n=0;try{n=(await z.blob()).size}catch(e){}m.sizes[t.u]=n;size+=n;done++;document.getElementById('oaBar').style.width=Math.round(done/tasks.length*100)+'%';document.getElementById('oaStatus').textContent=`${done} من ${tasks.length} مقطع`;document.getElementById('oaSize').textContent=bytes(size);if(t.last)m.items[`${r}:${t.s}`]={reciter:r,surah:t.s,at:new Date().toISOString()};save(m)}if(cancel)toast('تم إيقاف التنزيل');else toast('اكتمل تنزيل التلاوات ✓')}catch(e){console.error(e);toast('تعذر إكمال التنزيل. تحقق من الاتصال والمساحة')}finally{save(m);busy=false;setBusy(false);render()}}
  async function del(){if(busy||!chosen.size)return;const r=document.getElementById('oaReciter').value,m=read(),cache=await caches.open(CACHE);for(const s of chosen){for(const u of urls(s,r)){await cache.delete(u);delete m.sizes[u]}delete m.items[`${r}:${s}`]}save(m);chosen.clear();render();toast('تم حذف التلاوات المحددة')}
  async function delAll(){if(busy)return;if(!confirm('حذف جميع التلاوات المحفوظة على هذا الجهاز؟'))return;await caches.delete(CACHE);localStorage.removeItem(KEY);chosen.clear();render();toast('تم حذف جميع التلاوات')}
  const oldRender=typeof renderState==='function'?renderState:null;if(oldRender)renderState=function(){oldRender();if(document.getElementById('offlineAudio'))render()};
  inject();
})();