// Voice recitation test for Werd memorization review
(function(){
  const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;
  const INTERVALS={1:1,2:3,3:7,4:14,5:30};
  let scope='due',session=[],index=0,recognition=null,listening=false,finalTranscript='',interimTranscript='',analysis=null,rated=false;
  let stats={scores:[],again:0,hard:0,good:0,easy:0};

  function tracker(){
    if(!state.memorizationTracker||typeof state.memorizationTracker!=='object'||Array.isArray(state.memorizationTracker))state.memorizationTracker={};
    state.memorizationTracker={version:1,items:{},history:[],settings:{reminderEnabled:true,reminderTime:'19:30',dailyGoal:5},recitationHistory:[],...state.memorizationTracker};
    if(!state.memorizationTracker.items||typeof state.memorizationTracker.items!=='object'||Array.isArray(state.memorizationTracker.items))state.memorizationTracker.items={};
    if(!Array.isArray(state.memorizationTracker.history))state.memorizationTracker.history=[];
    if(!Array.isArray(state.memorizationTracker.recitationHistory))state.memorizationTracker.recitationHistory=[];
    return state.memorizationTracker;
  }
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function localDate(d=new Date()){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return`${y}-${m}-${day}`}
  function addDays(date,days){const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()+Number(days||0));return localDate(d)}
  function clamp(n){return Math.max(1,Math.min(5,Number(n)||1))}
  function allItems(){return Object.values(tracker().items).filter(x=>x&&!x.archived)}
  function dueItems(){const t=localDate();return allItems().filter(x=>String(x.nextReview||t)<=t)}
  function surahName(n){const list=(Array.isArray(window.surahs)&&surahs.length)?surahs:(window.fallbackSurahs||[]);return list.find(x=>Number(x.number)===Number(n))?.name||`سورة ${n}`}
  function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}

  function injectStyles(){if(document.getElementById('werdRecitationStyle'))return;const s=document.createElement('style');s.id='werdRecitationStyle';s.textContent=`
    .rtest-hero{background:linear-gradient(145deg,var(--green),#173f34);color:#fff;border-radius:24px;padding:19px;text-align:center}.rtest-hero small{opacity:.72}.rtest-title{font-size:20px;font-weight:900;margin:9px 0}.rtest-progress{height:7px;background:rgba(255,255,255,.16);border-radius:99px;overflow:hidden;margin-top:13px}.rtest-progress span{display:block;height:100%;background:#f0d39b;transition:width .25s}.rtest-scope{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.rtest-scope button.active{background:var(--green);color:#fff;border-color:var(--green)}.rtest-config{display:grid;grid-template-columns:1fr 1fr;gap:9px}.rtest-config select{width:100%;padding:10px;border:1px solid var(--line);border-radius:13px;background:var(--card);color:var(--ink)}.rtest-mic{width:88px;height:88px;border-radius:50%;border:0;background:var(--green);color:#fff;font-size:31px;box-shadow:0 10px 30px rgba(0,0,0,.15)}.rtest-mic.live{animation:rPulse 1.15s infinite}.rtest-live{min-height:95px;padding:14px;border:1px dashed var(--line);border-radius:18px;line-height:1.9;text-align:center}.rtest-live .interim{opacity:.48}.rtest-score{font-size:34px;font-weight:900}.rtest-words{display:flex;flex-wrap:wrap;gap:6px;line-height:1.8}.rtest-word{border-radius:10px;padding:5px 8px;font-size:14px}.rtest-match{background:rgba(77,128,101,.16);border:1px solid rgba(77,128,101,.32)}.rtest-miss{background:rgba(190,143,75,.14);border:1px solid rgba(190,143,75,.34)}.rtest-sub{background:rgba(170,83,73,.13);border:1px solid rgba(170,83,73,.28)}.rtest-sub small{display:block;color:var(--muted);font-size:8px}.rtest-extra{background:var(--sage);border-radius:12px;padding:9px;margin-top:10px;font-size:11px}.rtest-rate{display:grid;grid-template-columns:repeat(4,1fr);gap:6px}.rtest-rate button{font-size:10px;padding:9px 4px}.rtest-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.rtest-stat{background:var(--sage);padding:11px;border-radius:15px;text-align:center}.rtest-stat b{display:block;font-size:20px}.rtest-note{font-size:10px;line-height:1.7;color:var(--muted)}@keyframes rPulse{50%{transform:scale(1.06);box-shadow:0 0 0 14px rgba(30,85,68,.08)}}@media(max-width:390px){.rtest-scope{grid-template-columns:1fr}.rtest-config{grid-template-columns:1fr}.rtest-rate{grid-template-columns:1fr 1fr}}
  `;document.head.appendChild(s)}

  function inject(){
    injectStyles();tracker();const main=document.querySelector('main');if(!main)return;
    if(!document.getElementById('recitationTest')){const sec=document.createElement('section');sec.className='page';sec.id='recitationTest';sec.innerHTML=`
      <div class="section-title"><h3>التسميع بالصوت</h3><button class="smallbtn" id="rtestBack">اختبار الحفظ</button></div>
      <div class="rtest-hero"><small id="rtestHeroSmall">تسميع ومقارنة كلمةً بكلمة</small><div class="rtest-title" id="rtestHeroTitle">اختر جلسة التسميع</div><div id="rtestCounter">—</div><div class="rtest-progress"><span id="rtestProgress" style="width:0"></span></div></div>
      <div class="card" id="rtestSetup" style="margin-top:10px"><b>نطاق التسميع</b><div class="rtest-scope" style="margin-top:10px"><button class="smallbtn active" data-rscope="due">مستحق اليوم</button><button class="smallbtn" data-rscope="all">كل المحفوظ</button><button class="smallbtn" data-rscope="surah">سورة محددة</button></div><div class="rtest-config" style="margin-top:10px"><div><div class="muted" style="margin-bottom:5px">عدد الآيات</div><select id="rtestCount"><option value="1">آية واحدة</option><option value="3" selected>3 آيات</option><option value="5">5 آيات</option></select></div><div><div class="muted" style="margin-bottom:5px">السورة</div><select id="rtestSurah" disabled></select></div></div><div class="rtest-note" id="rtestSupport" style="margin-top:10px"></div><button class="primary" id="rtestStart" style="width:100%;margin-top:11px">ابدأ جلسة التسميع</button><div class="muted" id="rtestAvailable" style="text-align:center;margin-top:8px">—</div></div>
      <div class="card" id="rtestSession" style="display:none;margin-top:10px"><div class="row"><div><b id="rtestPrompt">—</b><div class="muted">اقرأ الآية كاملة من حفظك، ولا يظهر النص الصحيح قبل انتهاء التسميع.</div></div><span>🎙</span></div><div style="text-align:center;margin:17px 0"><button class="rtest-mic" id="rtestMic" aria-label="بدء التسجيل">🎙</button><div class="muted" id="rtestMicStatus" style="margin-top:8px">اضغط للبدء</div></div><div class="rtest-live" id="rtestLive"><span class="muted">سيظهر هنا النص الذي تعرّف عليه الجهاز من صوتك.</span></div><div class="row" style="margin-top:10px"><button class="secondary" id="rtestRetry" style="margin:0;flex:1" disabled>↺ إعادة التسميع</button><button class="primary" id="rtestAnalyze" style="margin:0;flex:1" disabled>تحليل التسميع</button></div></div>
      <div class="card" id="rtestAnalysis" style="display:none;margin-top:10px"><div class="row"><div><b>نتيجة المقارنة</b><div class="muted" id="rtestScoreMeta">—</div></div><div class="rtest-score" id="rtestScore">0٪</div></div><div style="margin-top:12px"><b style="font-size:12px">النص الصحيح ومواقع الاختلاف</b><div class="rtest-words" id="rtestWords" style="margin-top:8px"></div><div class="rtest-extra" id="rtestExtras" style="display:none"></div></div><div class="rtest-note" style="margin-top:11px">المقارنة مبنية على النص الذي أعاده نظام التعرف الصوتي وقد يخطئ في بعض الكلمات؛ لذلك لا يغيّر «ورد» مستوى إتقانك إلا بعد تقييمك أنت.</div><div style="margin-top:13px"><b>قيّم تسميعك</b><div class="rtest-rate" style="margin-top:8px"><button class="smallbtn" data-rrate="again">↺ أعدها</button><button class="smallbtn" data-rrate="hard">◔ صعب</button><button class="smallbtn" data-rrate="good">✓ جيد</button><button class="smallbtn" data-rrate="easy">★ متقن</button></div></div><button class="primary" id="rtestNext" disabled style="width:100%;margin-top:11px">التالي</button></div>
      <div class="card" id="rtestDone" style="display:none;margin-top:10px;text-align:center"><div style="font-size:38px">🎙✓</div><h3 style="margin:5px 0">اكتملت جلسة التسميع</h3><div class="rtest-summary" style="margin-top:12px"><div class="rtest-stat"><b id="rtestAvg">0٪</b><small>متوسط المطابقة</small></div><div class="rtest-stat"><b id="rtestStrong">0</b><small>جيد/متقن</small></div><div class="rtest-stat"><b id="rtestWeak">0</b><small>تحتاج تثبيت</small></div></div><div class="row" style="margin-top:12px"><button class="primary" id="rtestAgain" style="margin:0;flex:1">جلسة جديدة</button><button class="secondary" id="rtestTracker" style="margin:0;flex:1">متابعة الحفظ</button></div></div>`;main.appendChild(sec)}
    addEntries();wire();renderSetup();
  }

  function addEntries(){
    const mg=document.querySelector('#more .more-grid');if(mg&&!document.getElementById('moreRecitationTest')){const b=document.createElement('button');b.className='more-tile';b.id='moreRecitationTest';b.innerHTML='<span class="mi">🎙</span><b>التسميع بالصوت</b><small>قارن تسميعك بالنص الصحيح</small>';b.onclick=open;mg.insertBefore(b,mg.firstChild)}
    [['#memorizationTest .section-title','rtestFromTest','🎙 تسميع صوتي'],['#memorizationTracker .section-title','rtestFromTracker','🎙 تسميع'],['#memorization .section-title','rtestFromMem','🎙 تسميع']].forEach(([q,id,label])=>{const host=document.querySelector(q);if(host&&!document.getElementById(id)){const b=document.createElement('button');b.className='smallbtn';b.id=id;b.textContent=label;b.onclick=open;host.appendChild(b)}})
  }

  function wire(){const $=id=>document.getElementById(id);$('rtestBack').onclick=()=>{if(typeof window.openWerdMemorizationTest==='function')window.openWerdMemorizationTest();else if(typeof window.openWerdMemorizationTracker==='function')window.openWerdMemorizationTracker()};$('rtestStart').onclick=startSession;$('rtestMic').onclick=toggleMic;$('rtestRetry').onclick=retry;$('rtestAnalyze').onclick=analyzeCurrent;$('rtestNext').onclick=next;$('rtestAgain').onclick=reset;$('rtestTracker').onclick=()=>window.openWerdMemorizationTracker?.();$('rtestSurah').onchange=renderSetup;document.querySelectorAll('[data-rscope]').forEach(b=>b.onclick=()=>{scope=b.dataset.rscope;document.querySelectorAll('[data-rscope]').forEach(x=>x.classList.toggle('active',x.dataset.rscope===scope));$('rtestSurah').disabled=scope!=='surah';renderSetup()});document.querySelectorAll('[data-rrate]').forEach(b=>b.onclick=()=>rateCurrent(b.dataset.rrate))}

  function open(){stopMic();reset(false);go('recitationTest');renderSetup()} window.openWerdRecitationTest=open;
  function candidates(){let a=scope==='due'?dueItems():allItems();if(scope==='surah'){const s=Number(document.getElementById('rtestSurah')?.value||0);a=a.filter(x=>Number(x.surah)===s)}return a}
  function renderSetup(){const sel=document.getElementById('rtestSurah');if(!sel)return;const prev=sel.value,map=new Map();allItems().forEach(x=>map.set(Number(x.surah),x.surahName||surahName(x.surah)));const ss=[...map.entries()].sort((a,b)=>a[0]-b[0]);sel.innerHTML=ss.length?ss.map(([n,name])=>`<option value="${n}">${n}. ${esc(name)}</option>`).join(''):'<option value="">لا توجد سور محفوظة</option>';if(prev&&ss.some(x=>String(x[0])===prev))sel.value=prev;const n=candidates().length;document.getElementById('rtestAvailable').textContent=scope==='due'?`${n} آية مستحقة متاحة للتسميع`:`${n} آية متاحة للتسميع`;const support=document.getElementById('rtestSupport'),start=document.getElementById('rtestStart');if(!SpeechRecognition){support.textContent='التعرف الصوتي غير مدعوم في هذا المتصفح. يمكنك استخدام «اختبار الحفظ» النصي بدلًا منه.';start.disabled=true}else{support.textContent='عند بدء الميكروفون قد تعتمد عملية تحويل الصوت إلى نص على خدمة يوفرها المتصفح أو نظام الجهاز. لا يحفظ «ورد» الملف الصوتي أو نص التسميع في حسابك.';start.disabled=!n}}

  function startSession(){const pool=candidates();if(!SpeechRecognition)return toast('التعرف الصوتي غير مدعوم على هذا المتصفح');if(!pool.length)return toast('لا توجد آيات في هذا النطاق');const count=Math.min(pool.length,Number(document.getElementById('rtestCount').value)||3);session=shuffle(pool.slice()).slice(0,count);index=0;stats={scores:[],again:0,hard:0,good:0,easy:0};document.getElementById('rtestSetup').style.display='none';document.getElementById('rtestDone').style.display='none';document.getElementById('rtestSession').style.display='block';showQuestion()}
  function showQuestion(){stopMic();analysis=null;rated=false;finalTranscript='';interimTranscript='';const x=session[index];if(!x)return finish();document.getElementById('rtestHeroSmall').textContent='اقرأ من حفظك';document.getElementById('rtestHeroTitle').textContent=`${x.surahName||surahName(x.surah)} • الآية ${x.ayah}`;document.getElementById('rtestPrompt').textContent=`${x.surahName||surahName(x.surah)} — الآية ${x.ayah}`;document.getElementById('rtestCounter').textContent=`${index+1} من ${session.length}`;document.getElementById('rtestProgress').style.width=`${Math.round(index/session.length*100)}%`;document.getElementById('rtestLive').innerHTML='<span class="muted">سيظهر هنا النص الذي تعرّف عليه الجهاز من صوتك.</span>';document.getElementById('rtestMicStatus').textContent='اضغط للبدء';document.getElementById('rtestRetry').disabled=true;document.getElementById('rtestAnalyze').disabled=true;document.getElementById('rtestAnalysis').style.display='none';document.getElementById('rtestSession').style.display='block';document.querySelectorAll('[data-rrate]').forEach(b=>b.disabled=false);document.getElementById('rtestNext').disabled=true;document.getElementById('rtestNext').textContent=index===session.length-1?'إنهاء الجلسة':'التالي'}

  function makeRecognition(){const r=new SpeechRecognition();r.lang='ar-SA';r.continuous=true;r.interimResults=true;r.maxAlternatives=1;r.onstart=()=>{listening=true;document.getElementById('rtestMic').classList.add('live');document.getElementById('rtestMic').textContent='■';document.getElementById('rtestMicStatus').textContent='أستمع الآن… اضغط للإيقاف'};r.onresult=e=>{let interim='';for(let i=e.resultIndex;i<e.results.length;i++){const text=e.results[i][0]?.transcript||'';if(e.results[i].isFinal)finalTranscript+=(finalTranscript?' ':'')+text.trim();else interim+=text}interimTranscript=interim;renderTranscript()};r.onerror=e=>{console.warn('Speech recognition',e.error);if(e.error==='not-allowed'||e.error==='service-not-allowed')toast('اسمح للميكروفون لاستخدام التسميع الصوتي');else if(e.error!=='aborted'&&e.error!=='no-speech')toast('تعذر التعرف على الصوت، حاول مرة أخرى')};r.onend=()=>{listening=false;const mic=document.getElementById('rtestMic');if(mic){mic.classList.remove('live');mic.textContent='🎙'}const has=finalTranscript.trim().length>0;if(document.getElementById('rtestMicStatus'))document.getElementById('rtestMicStatus').textContent=has?'تم التقاط التسميع ✓':'اضغط للبدء';if(document.getElementById('rtestRetry'))document.getElementById('rtestRetry').disabled=!has;if(document.getElementById('rtestAnalyze'))document.getElementById('rtestAnalyze').disabled=!has};return r}
  function toggleMic(){if(listening){stopMic();return}finalTranscript='';interimTranscript='';renderTranscript();try{recognition=makeRecognition();recognition.start()}catch(e){console.error(e);toast('تعذر تشغيل الميكروفون')}}
  function stopMic(){if(recognition){try{recognition.stop()}catch(e){}recognition=null}listening=false;const mic=document.getElementById('rtestMic');if(mic){mic.classList.remove('live');mic.textContent='🎙'}}
  function retry(){stopMic();finalTranscript='';interimTranscript='';analysis=null;document.getElementById('rtestRetry').disabled=true;document.getElementById('rtestAnalyze').disabled=true;document.getElementById('rtestLive').innerHTML='<span class="muted">اضغط الميكروفون وأعد قراءة الآية.</span>';document.getElementById('rtestMicStatus').textContent='جاهز للإعادة'}
  function renderTranscript(){const box=document.getElementById('rtestLive');if(!box)return;const f=finalTranscript.trim(),i=interimTranscript.trim();box.innerHTML=(f?`<span>${esc(f)}</span>`:'')+(i?` <span class="interim">${esc(i)}</span>`:'')||'<span class="muted">أستمع…</span>'}

  function normalizeWord(v){return String(v||'').normalize('NFKD').replace(/[\u0610-\u061A\u064B-\u065F\u0670\u06D6-\u06ED]/g,'').replace(/ـ/g,'').replace(/[إأآٱ]/g,'ا').replace(/ؤ/g,'و').replace(/ئ/g,'ي').replace(/ى/g,'ي').replace(/[^\u0621-\u063A\u0641-\u064A0-9]/g,'').trim()}
  function tokens(v){return String(v||'').split(/\s+/).map(raw=>({raw:raw.replace(/[۝۞﴿﴾]/g,''),norm:normalizeWord(raw)})).filter(x=>x.norm)}
  function align(expected,actual){const m=expected.length,n=actual.length,dp=Array.from({length:m+1},()=>Array(n+1).fill(0)),op=Array.from({length:m+1},()=>Array(n+1).fill(''));for(let i=1;i<=m;i++){dp[i][0]=i;op[i][0]='del'}for(let j=1;j<=n;j++){dp[0][j]=j;op[0][j]='ins'}for(let i=1;i<=m;i++)for(let j=1;j<=n;j++){const same=expected[i-1].norm===actual[j-1].norm,sub=dp[i-1][j-1]+(same?0:1),del=dp[i-1][j]+1,ins=dp[i][j-1]+1;const best=Math.min(sub,del,ins);dp[i][j]=best;op[i][j]=best===sub?(same?'match':'sub'):(best===del?'del':'ins')}let i=m,j=n,out=[];while(i>0||j>0){const k=op[i][j];if(k==='match'||k==='sub'){out.push({type:k,e:expected[i-1],a:actual[j-1]});i--;j--}else if(k==='del'){out.push({type:'del',e:expected[i-1]});i--}else{out.push({type:'ins',a:actual[j-1]});j--}}out.reverse();const correct=out.filter(x=>x.type==='match').length,total=m,score=total?Math.round(correct/total*100):0;return{out,correct,total,score,distance:dp[m][n]}}
  async function fetchAyah(x){const key=`${x.surah}:${x.ayah}`;window.__werdAyahTextCache=window.__werdAyahTextCache||new Map();if(window.__werdAyahTextCache.has(key))return window.__werdAyahTextCache.get(key);const r=await fetch(`${API_QURAN}/ayah/${x.surah}:${x.ayah}/quran-uthmani`);if(!r.ok)throw new Error('quran');const j=await r.json(),text=j?.data?.text;if(!text)throw new Error('quran');window.__werdAyahTextCache.set(key,text);return text}

  async function analyzeCurrent(){if(!finalTranscript.trim())return toast('سجّل تسميعك أولًا');stopMic();const btn=document.getElementById('rtestAnalyze');btn.disabled=true;btn.textContent='جاري المقارنة…';try{const x=session[index],correctText=await fetchAyah(x);analysis=align(tokens(correctText),tokens(finalTranscript));analysis.correctText=correctText;renderAnalysis()}catch(e){console.error(e);toast('تعذر تحميل النص الصحيح للمقارنة');btn.disabled=false}finally{btn.textContent='تحليل التسميع'}}
  function renderAnalysis(){const a=analysis;if(!a)return;document.getElementById('rtestSession').style.display='none';document.getElementById('rtestAnalysis').style.display='block';document.getElementById('rtestScore').textContent=`${a.score}٪`;const errs=a.out.filter(x=>x.type!=='match');document.getElementById('rtestScoreMeta').textContent=`${a.correct} من ${a.total} كلمة مطابقة • ${errs.length} موضع يحتاج مراجعة`;const extras=[];document.getElementById('rtestWords').innerHTML=a.out.filter(x=>x.type!=='ins').map(x=>{if(x.type==='match')return`<span class="rtest-word rtest-match">${esc(x.e.raw)}</span>`;if(x.type==='del')return`<span class="rtest-word rtest-miss">${esc(x.e.raw)}<small>لم تُلتقط</small></span>`;return`<span class="rtest-word rtest-sub">${esc(x.e.raw)}<small>سُمعت: ${esc(x.a?.raw||'—')}</small></span>`}).join('');a.out.filter(x=>x.type==='ins').forEach(x=>extras.push(x.a.raw));const ex=document.getElementById('rtestExtras');if(extras.length){ex.style.display='block';ex.innerHTML=`<b>كلمات إضافية التقطها الجهاز:</b> ${extras.map(esc).join(' • ')}`}else ex.style.display='none'}

  function rateCurrent(rating){if(!analysis||rated)return;const x=session[index],t=tracker(),id=x.id||`${x.surah}:${x.ayah}`,item=t.items[id];if(!item)return toast('تعذر العثور على الآية في سجل الحفظ');const before=clamp(item.mastery);let after=before,days=1,success=true;if(rating==='again'){after=1;days=1;success=false;item.lapses=(Number(item.lapses)||0)+1}else if(rating==='hard'){after=before;days=Math.max(1,Math.ceil((INTERVALS[after]||1)/2))}else if(rating==='good'){after=Math.min(5,before+1);days=INTERVALS[after]||7}else if(rating==='easy'){after=Math.min(5,before+2);days=Math.max(INTERVALS[after]||14,7)}const today=localDate();item.mastery=after;item.lastReviewed=new Date().toISOString();item.nextReview=addDays(today,days);item.reviewCount=(Number(item.reviewCount)||0)+1;if(success)item.successCount=(Number(item.successCount)||0)+1;t.history.unshift({at:new Date().toISOString(),date:today,id,surah:item.surah,ayah:item.ayah,rating,before,after,nextReview:item.nextReview,source:'voice-recitation'});if(t.history.length>500)t.history.length=500;t.recitationHistory.unshift({at:new Date().toISOString(),date:today,id,surah:item.surah,ayah:item.ayah,score:analysis.score,correct:analysis.correct,total:analysis.total,rating});if(t.recitationHistory.length>200)t.recitationHistory.length=200;stats.scores.push(analysis.score);stats[rating]=(stats[rating]||0)+1;rated=true;save();document.querySelectorAll('[data-rrate]').forEach(b=>b.disabled=true);document.getElementById('rtestNext').disabled=false;toast('تم حفظ تقييم التسميع ✓')}
  function next(){if(!rated)return;index++;if(index>=session.length)finish();else showQuestion()}
  function finish(){stopMic();document.getElementById('rtestSession').style.display='none';document.getElementById('rtestAnalysis').style.display='none';document.getElementById('rtestDone').style.display='block';document.getElementById('rtestHeroSmall').textContent='اكتملت الجلسة';document.getElementById('rtestHeroTitle').textContent='نتيجة التسميع';document.getElementById('rtestCounter').textContent=`${session.length} آية`;document.getElementById('rtestProgress').style.width='100%';const avg=stats.scores.length?Math.round(stats.scores.reduce((a,b)=>a+b,0)/stats.scores.length):0;document.getElementById('rtestAvg').textContent=`${avg}٪`;document.getElementById('rtestStrong').textContent=(stats.good||0)+(stats.easy||0);document.getElementById('rtestWeak').textContent=(stats.again||0)+(stats.hard||0)}
  function reset(showSetup=true){stopMic();session=[];index=0;analysis=null;rated=false;finalTranscript='';interimTranscript='';stats={scores:[],again:0,hard:0,good:0,easy:0};if(document.getElementById('rtestSetup'))document.getElementById('rtestSetup').style.display=showSetup?'block':'block';if(document.getElementById('rtestSession'))document.getElementById('rtestSession').style.display='none';if(document.getElementById('rtestAnalysis'))document.getElementById('rtestAnalysis').style.display='none';if(document.getElementById('rtestDone'))document.getElementById('rtestDone').style.display='none';if(document.getElementById('rtestHeroTitle'))document.getElementById('rtestHeroTitle').textContent='اختر جلسة التسميع';if(document.getElementById('rtestCounter'))document.getElementById('rtestCounter').textContent='—';if(document.getElementById('rtestProgress'))document.getElementById('rtestProgress').style.width='0';renderSetup()}

  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject);else inject();
})();