const APP_CACHE='werd-v53';
const RUNTIME_CACHE='werd-runtime-v53';
const MUSHAF_OFFLINE_CACHE='werd-mushaf-offline-v1';
const AUDIO_OFFLINE_CACHE='werd-audio-offline-v1';
const APP_SHELL=['./','./index.html','./app.css','./app.js','./notifications.js','./features.js','./audio-engine.js','./reader.js','./listening.js','./listening-ios-fix.js','./prayer.js','./more.js','./search.js','./iman.js','./home.js','./progress.js','./onboarding.js','./onboarding-skip-fix.js','./profile.js','./mushaf-core-v2.js','./offline-mushaf.js','./offline-audio.js','./playlist.js','./memorization.js','./memorization-tracker.js','./memorization-test.js','./recitation-test.js','./weakness-analysis.js','./daily-memorization-plan.js','./weekly-memorization-plan.js','./long-term-memorization-goal.js','./monthly-memorization-dashboard.js','./achievement-report.js','./advanced-achievements.js','./memorization-journey.js','./desktop-layout.js','./premium-islamic-theme.js','./desktop-premium-home.js','./reference-sidebar.js','./mobile-layout-fix.js','./mobile-home-hub.js','./mobile-memorization-hub.js','./deep-link.js','./manifest.webmanifest','./icon.svg'];
self.addEventListener('install',event=>{event.waitUntil(caches.open(APP_CACHE).then(cache=>cache.addAll(APP_SHELL)));self.skipWaiting();});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>![APP_CACHE,RUNTIME_CACHE,MUSHAF_OFFLINE_CACHE,AUDIO_OFFLINE_CACHE].includes(k)).map(k=>caches.delete(k)))));self.clients.claim();});
async function rangedResponse(req,saved){const range=req.headers.get('range');if(!range||!saved)return saved;const m=/bytes=(\d+)-(\d*)/.exec(range);if(!m)return saved;const blob=await saved.blob(),size=blob.size,start=Number(m[1]||0),end=m[2]?Math.min(Number(m[2]),size-1):size-1;if(start>=size)return new Response(null,{status:416,headers:{'Content-Range':`bytes */${size}`}});const part=blob.slice(start,end+1),headers=new Headers(saved.headers);headers.set('Content-Range',`bytes ${start}-${end}/${size}`);headers.set('Accept-Ranges','bytes');headers.set('Content-Length',String(part.size));headers.set('Content-Type',saved.headers.get('Content-Type')||'audio/mpeg');return new Response(part,{status:206,statusText:'Partial Content',headers});}
self.addEventListener('fetch',event=>{const req=event.request;if(req.method!=='GET')return;const url=new URL(req.url);
if(url.origin===self.location.origin&&url.pathname.startsWith('/api/mushaf/')){event.respondWith(fetch(req,{cache:'no-store'}));return;}
if(url.hostname.includes('cdn.islamic.network')&&url.pathname.includes('/quran/audio')){event.respondWith((async()=>{const cache=await caches.open(AUDIO_OFFLINE_CACHE),saved=await cache.match(req,{ignoreVary:true});if(saved)return rangedResponse(req,saved);return fetch(req)})());return;}
if(url.hostname.includes('hisnmuslim.com')&&url.pathname.includes('/audio/')){event.respondWith(fetch(req));return;}
if(req.mode==='navigate'){event.respondWith(fetch(req).then(res=>{const copy=res.clone();caches.open(APP_CACHE).then(c=>c.put('./index.html',copy));return res;}).catch(()=>caches.match('./index.html')));return;}
if(url.hostname.includes('alquran.cloud')||url.hostname.includes('islamic.network')||url.hostname.includes('aladhan.com')||url.hostname.includes('hisnmuslim.com')||url.hostname.includes('raw.githubusercontent.com')||url.hostname.includes('cdn.jsdelivr.net')||url.hostname.includes('api.quran.com')){event.respondWith(caches.open(RUNTIME_CACHE).then(async cache=>{const cached=await cache.match(req);const network=fetch(req).then(res=>{if(res&&res.status===200)cache.put(req,res.clone());return res;}).catch(()=>cached);return cached||network;}));return;}
if(url.origin===self.location.origin){const fresh=/\.(?:js|css)$/.test(url.pathname);if(fresh){event.respondWith(fetch(req,{cache:'no-store'}).then(res=>{if(res&&res.status===200){const copy=res.clone();caches.open(APP_CACHE).then(c=>c.put(req,copy));}return res;}).catch(()=>caches.match(req)));return;}event.respondWith(caches.match(req).then(cached=>cached||fetch(req).then(res=>{if(res&&res.status===200){const copy=res.clone();caches.open(APP_CACHE).then(c=>c.put(req,copy));}return res;})));}});
self.addEventListener('push',event=>{let data={};try{data=event.data?event.data.json():{}}catch(e){data={body:event.data?.text()||'لديك تذكير جديد من ورد'}}const title=data.title||'ورد 🌿';event.waitUntil(self.registration.showNotification(title,{body:data.body||'حان وقت وردك اليومي.',icon:'./icon.svg',badge:'./icon.svg',dir:'rtl',lang:'ar',tag:data.tag||'werd-reminder',renotify:true,data:{url:data.url||'./'}}));});
self.addEventListener('notificationclick',event=>{event.notification.close();const target=event.notification.data?.url||'./';event.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(list=>{for(const client of list){if('focus'in client){client.navigate(target).catch(()=>{});return client.focus();}}return clients.openWindow?clients.openWindow(target):undefined;}));});